'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { AlertTriangle, ArrowLeft, BrainCircuit, Building2, CircleDot, GitBranch, LoaderCircle, RefreshCw, Search, Target, UserRound, Workflow } from 'lucide-react';

type NodeKind='goal'|'task'|'artifact'|'person'|'organization';
type Node={id:string;kind:NodeKind;label:string;description?:string;status?:string;priority?:string;source:string;sourceId:string;tags:string[]};
type Edge={id:string;from:string;to:string;type:string;confidence:number;source:'explicit'|'inferred';reason?:string};
type Insight={id:string;severity:'critical'|'high'|'normal'|'info';kind:string;title:string;summary:string;nodeIds:string[]};
type Model={generatedAt:string;nodes:Node[];edges:Edge[];insights:Insight[];stats:{nodes:number;edges:number;explicitEdges:number;inferredEdges:number;goals:number;tasks:number;artifacts:number;people:number;organizations:number;orphanTasks:number;disconnectedGoals:number;attentionRelationships:number}};

const panel={border:'1px solid #1d3d59',background:'#091827',borderRadius:16,padding:16} as const;
const button={border:'1px solid #315874',background:'#0d2133',color:'#e8f5ff',borderRadius:999,padding:'9px 13px',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:7} as const;
const input={background:'#071421',border:'1px solid #294963',color:'#eaf4ff',borderRadius:999,padding:'10px 14px',width:'100%'} as const;
const kindIcon:Record<NodeKind,ReactNode>={goal:<Target size={15}/>,task:<Workflow size={15}/>,artifact:<BrainCircuit size={15}/>,person:<UserRound size={15}/>,organization:<Building2 size={15}/>};

export default function WorldModelPage(){
  const [data,setData]=useState<Model|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState<string>('');
  useEffect(()=>{void fetch('/api/identity',{method:'POST',cache:'no-store'}).then(()=>load()).catch(()=>load());},[]);
  async function load(){setBusy(true);setError('');try{const r=await fetch('/api/world-model',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'World Model failed to load.');setData(j);}catch(e){setError(e instanceof Error?e.message:'World Model failed.');}finally{setBusy(false);}}
  const nodeById=useMemo(()=>new Map((data?.nodes||[]).map(node=>[node.id,node])),[data]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return data?.nodes||[];const terms=q.split(/\s+/).filter(Boolean);return (data?.nodes||[]).filter(node=>{const text=[node.label,node.description,node.kind,node.status,node.priority,...node.tags].filter(Boolean).join(' ').toLowerCase();return terms.every(term=>text.includes(term));});},[data,query]);
  const selectedNode=selected?nodeById.get(selected):undefined;
  const selectedEdges=useMemo(()=>selected?(data?.edges||[]).filter(edge=>edge.from===selected||edge.to===selected).slice(0,40):[],[data,selected]);
  const severity=(value:string)=>value==='critical'?'#ff9eab':value==='high'?'#ffd076':value==='info'?'#8dc6ff':'#b7c8d7';
  return <main style={{minHeight:'100vh',background:'#06111f',color:'#edf7ff',padding:22,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1500,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap',marginBottom:18}}><Link href="/mission-control" style={{color:'#9ecbff',textDecoration:'none',display:'flex',gap:7,alignItems:'center'}}><ArrowLeft size={17}/> Mission Control</Link><div style={{textAlign:'center'}}><div style={{fontSize:11,letterSpacing:2,color:'#75a9d6'}}>ELP OPERATIONAL INTELLIGENCE</div><h1 style={{margin:'4px 0',fontSize:34}}>World Model</h1><div style={{fontSize:12,color:'#77dfb4'}}>GOALS · EXECUTION · DECISIONS · PEOPLE · ORGANIZATIONS · DEPENDENCIES</div></div><button onClick={()=>void load()} disabled={busy} style={button}>{busy?<LoaderCircle size={15}/>:<RefreshCw size={15}/>} Refresh</button></header>
    {error&&<div style={{padding:12,border:'1px solid #773142',background:'#2b1119',borderRadius:10,color:'#ffd8df',marginBottom:12}}>{error}</div>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,marginBottom:14}}>{[
      ['Nodes',data?.stats.nodes||0,<CircleDot key="n" size={18}/>],['Links',data?.stats.edges||0,<GitBranch key="l" size={18}/>],['Goals',data?.stats.goals||0,<Target key="g" size={18}/>],['Tasks',data?.stats.tasks||0,<Workflow key="t" size={18}/>],['People',data?.stats.people||0,<UserRound key="p" size={18}/>],['Orphan tasks',data?.stats.orphanTasks||0,<AlertTriangle key="o" size={18}/>],['Goal gaps',data?.stats.disconnectedGoals||0,<AlertTriangle key="d" size={18}/>],['Inferred links',data?.stats.inferredEdges||0,<BrainCircuit key="i" size={18}/>],
    ].map(([label,value,icon])=><div key={String(label)} style={panel}><div style={{display:'flex',justifyContent:'space-between',fontSize:10,color:'#78a8cf'}}><span>{label}</span>{icon}</div><div style={{fontSize:27,fontWeight:750,marginTop:5}}>{String(value)}</div></div>)}</section>
    <section style={{...panel,marginBottom:14}}><div style={{display:'flex',alignItems:'center',gap:10}}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the operational graph — person, company, goal, task, decision…" style={{...input,border:'none',outline:'none',padding:0}}/></div></section>
    <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.1fr) minmax(330px,.9fr)',gap:14,alignItems:'start'}}>
      <div style={{display:'grid',gap:14}}><section style={panel}><div style={{fontSize:11,letterSpacing:1.3,color:'#6f9dc8',marginBottom:10}}>CROSS-DOMAIN ATTENTION</div>{(data?.insights||[]).length?(data?.insights||[]).slice(0,20).map(item=><button key={item.id} onClick={()=>item.nodeIds[0]&&setSelected(item.nodeIds[0])} style={{display:'block',width:'100%',textAlign:'left',border:'0',borderTop:'1px solid #17334b',background:'transparent',color:'#eaf4ff',padding:'11px 2px',cursor:'pointer'}}><div style={{fontSize:11,color:severity(item.severity)}}>{item.severity.toUpperCase()} · {item.kind.replaceAll('_',' ')}</div><b>{item.title}</b><div style={{fontSize:12,color:'#9fb6c8',marginTop:3}}>{item.summary}</div></button>):<div style={{color:'#8ba2b5'}}>No cross-domain exceptions detected.</div>}</section>
      <section style={panel}><div style={{fontSize:11,letterSpacing:1.3,color:'#6f9dc8',marginBottom:10}}>ENTITY INDEX · {visible.length}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:8}}>{visible.slice(0,100).map(node=><button key={node.id} onClick={()=>setSelected(node.id)} style={{border:selected===node.id?'1px solid #76b9ee':'1px solid #1b3850',background:selected===node.id?'#10263a':'#071522',color:'#eaf4ff',borderRadius:12,padding:11,textAlign:'left',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,color:'#79acd5',fontSize:10}}><span style={{display:'flex',gap:6,alignItems:'center'}}>{kindIcon[node.kind]} {node.kind.toUpperCase()}</span><span>{node.priority||node.status||''}</span></div><b style={{display:'block',marginTop:6}}>{node.label}</b><div style={{fontSize:11,color:'#8fa8bc',marginTop:4}}>{(node.description||node.tags.slice(0,3).join(' · ')).slice(0,140)}</div></button>)}</div></section></div>
      <aside style={{...panel,position:'sticky',top:12}}><div style={{fontSize:11,letterSpacing:1.3,color:'#6f9dc8'}}>CONTEXT</div>{selectedNode?<><div style={{display:'flex',gap:8,alignItems:'center',marginTop:10,color:'#8dc6ff'}}>{kindIcon[selectedNode.kind]} {selectedNode.kind.toUpperCase()}</div><h2 style={{margin:'7px 0'}}>{selectedNode.label}</h2>{selectedNode.description&&<p style={{fontSize:12,color:'#b5c8d8'}}>{selectedNode.description}</p>}<div style={{fontSize:11,color:'#849eb3'}}>{selectedNode.status||'—'}{selectedNode.priority?` · ${selectedNode.priority}`:''} · source {selectedNode.source}</div><div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:10}}>{selectedNode.tags.slice(0,10).map(tag=><span key={tag} style={{border:'1px solid #294b65',borderRadius:999,padding:'4px 7px',fontSize:10}}>{tag}</span>)}</div><div style={{fontSize:11,letterSpacing:1.2,color:'#6f9dc8',marginTop:18}}>CONNECTED TO · {selectedEdges.length}</div>{selectedEdges.length?selectedEdges.map(edge=>{const other=nodeById.get(edge.from===selected?edge.to:edge.from);return <button key={edge.id} onClick={()=>other&&setSelected(other.id)} style={{display:'block',width:'100%',textAlign:'left',border:'0',borderTop:'1px solid #17334b',background:'transparent',color:'#eaf4ff',padding:'10px 0',cursor:'pointer'}}><div style={{fontSize:10,color:edge.source==='explicit'?'#77dfb4':'#ffd076'}}>{edge.type.replaceAll('_',' ').toUpperCase()} · {edge.source.toUpperCase()} · {Math.round(edge.confidence*100)}%</div><b>{other?.label||'Unknown node'}</b>{edge.reason&&<div style={{fontSize:11,color:'#8fa8bc'}}>{edge.reason}</div>}</button>}):<div style={{fontSize:12,color:'#8099ad',marginTop:8}}>No graph connections yet.</div>}</>:<div style={{color:'#8099ad',marginTop:10}}>Select an entity or an insight to inspect its strategic context.</div>}</aside>
    </section>
    <footer style={{fontSize:10,color:'#617d95',marginTop:18}}>World Model is read-only. Explicit links come from ELP's durable ledgers. Inferred links are confidence-scored semantic associations and never overwrite source records.</footer>
  </div></main>;
}
