'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Copy, KeyRound, Laptop, LoaderCircle, RefreshCw, ShieldCheck, UserPlus, UserX, Wifi, WifiOff } from 'lucide-react';

type Role = 'owner'|'executive'|'assistant'|'operator'|'viewer';
type Principal = { id:string; displayName:string; role:Role; capabilities:string[]; status:'active'|'revoked'; createdAt:string };
type Device = { id:string; label:string; platform:string; agentVersion?:string; principalId:string; allowedCommands:string[]; status:'active'|'revoked'; lastSeenAt?:string; online:boolean };
type Audit = { id:string; actorPrincipalId:string; action:string; target?:string; detail?:string; createdAt:string };
type Snapshot = { principals:Principal[]; devices:Device[]; audit:Audit[]; stats:{activePrincipals:number;activeDevices:number;onlineDevices:number} };

const panel: React.CSSProperties = { background:'#091725',border:'1px solid #1d3c56',borderRadius:14,padding:16 };
const button: React.CSSProperties = { background:'#10273a',border:'1px solid #315676',borderRadius:9,color:'#e9f5ff',padding:'9px 12px',cursor:'pointer',display:'inline-flex',gap:7,alignItems:'center' };
const input: React.CSSProperties = { background:'#06111f',border:'1px solid #294863',borderRadius:8,color:'#e9f5ff',padding:'10px 11px',width:'100%' };

export default function AuthorityControlPage(){
  const [data,setData]=useState<Snapshot|null>(null); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [name,setName]=useState(''); const [role,setRole]=useState<Role>('assistant'); const [enrollment,setEnrollment]=useState<{token:string;expiresAt:string;principal:string}|null>(null);
  const load=useCallback(async()=>{setBusy('load');setError('');try{await fetch('/api/identity',{method:'POST',cache:'no-store'});const r=await fetch('/api/authority-control',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load authority control.');setData(j);}catch(e){setError(e instanceof Error?e.message:'Could not load authority control.');}finally{setBusy('');}},[]);
  useEffect(()=>{void load();},[load]);
  async function action(body:Record<string,unknown>){const r=await fetch('/api/authority-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Authority action failed.');return j;}
  async function create(){setBusy('create');setError('');try{const j=await action({action:'create-principal',displayName:name,role});setData(j.snapshot);setName('');setMessage('Principal created with least-privilege role capabilities.');}catch(e){setError(e instanceof Error?e.message:'Could not create principal.');}finally{setBusy('');}}
  async function revokePrincipal(id:string){setBusy(`revoke-${id}`);setError('');try{const j=await action({action:'revoke-principal',principalId:id});setData(j.snapshot);setMessage('Principal revoked. Existing authority checks will fail closed.');}catch(e){setError(e instanceof Error?e.message:'Could not revoke principal.');}finally{setBusy('');}}
  async function enroll(principal:Principal){setBusy(`enroll-${principal.id}`);setError('');try{const j=await action({action:'create-enrollment',principalId:principal.id,label:`${principal.displayName} companion`});setEnrollment({token:j.enrollment.enrollmentToken,expiresAt:j.enrollment.expiresAt,principal:principal.displayName});setMessage('One-time companion enrollment created. It expires in 30 minutes.');}catch(e){setError(e instanceof Error?e.message:'Could not create enrollment.');}finally{setBusy('');}}
  async function revokeDevice(id:string){setBusy(`device-${id}`);setError('');try{const j=await action({action:'revoke-device',deviceId:id});setData(j.snapshot);setMessage('Companion revoked and its signed token invalidated.');}catch(e){setError(e instanceof Error?e.message:'Could not revoke companion.');}finally{setBusy('');}}
  async function copyToken(){if(!enrollment)return;await navigator.clipboard.writeText(enrollment.token);setMessage('Enrollment token copied.');}
  const principalName=(id:string)=>data?.principals.find(p=>p.id===id)?.displayName||id;
  return <main style={{minHeight:'100vh',background:'#06111f',color:'#edf7ff',padding:22,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1400,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap',marginBottom:18}}><div><Link href="/mission-control" style={{color:'#9ecbff',textDecoration:'none',display:'flex',gap:7,alignItems:'center'}}><ArrowLeft size={17}/> Mission Control</Link><div style={{fontSize:11,letterSpacing:2,color:'#75a9d6',marginTop:14}}>ELP TRUST & DEVICE CONTROL PLANE</div><h1 style={{margin:'5px 0',fontSize:34}}>Principal Authority</h1><p style={{margin:0,color:'#91aabd'}}>Define who ELP can act for, what they can approve, and which enrolled devices may execute local commands.</p></div><button style={button} onClick={()=>void load()} disabled={busy==='load'}>{busy==='load'?<LoaderCircle size={15}/>:<RefreshCw size={15}/>} Refresh</button></header>
    {error&&<div style={{padding:12,border:'1px solid #78384a',background:'#2a1119',borderRadius:10,color:'#ffd7df',marginBottom:12}}>{error}</div>}{message&&<div style={{padding:12,border:'1px solid #2e6b53',background:'#0a281e',borderRadius:10,color:'#baf5da',marginBottom:12}}>{message}</div>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginBottom:14}}>{[['Active principals',data?.stats.activePrincipals||0],['Active companions',data?.stats.activeDevices||0],['Online companions',data?.stats.onlineDevices||0]].map(([k,v])=><div key={String(k)} style={panel}><div style={{fontSize:11,color:'#7fa4c1',textTransform:'uppercase'}}>{k}</div><div style={{fontSize:30,fontWeight:800,marginTop:6}}>{v}</div></div>)}</section>
    <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.2fr) minmax(320px,.8fr)',gap:14,alignItems:'start'}}>
      <div style={{display:'grid',gap:14}}>
        <section style={panel}><div style={{display:'flex',gap:8,alignItems:'center'}}><ShieldCheck size={18}/><h2 style={{margin:0}}>Principals</h2></div><div style={{display:'grid',gap:10,marginTop:12}}>{(data?.principals||[]).map(p=><div key={p.id} style={{padding:12,border:'1px solid #21415a',borderRadius:10,opacity:p.status==='revoked'?.55:1}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'}}><div><b style={{fontSize:16}}>{p.displayName}</b><div style={{fontSize:12,color:'#83a4bd',marginTop:4}}>{p.role.toUpperCase()} · {p.status.toUpperCase()}</div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{p.status==='active'&&<button style={button} onClick={()=>void enroll(p)} disabled={busy===`enroll-${p.id}`}><Laptop size={14}/> Enroll device</button>}{p.role!=='owner'&&p.status==='active'&&<button style={button} onClick={()=>void revokePrincipal(p.id)} disabled={busy===`revoke-${p.id}`}><UserX size={14}/> Revoke</button>}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{p.capabilities.map(c=><span key={c} style={{fontSize:10,padding:'4px 7px',borderRadius:99,background:'#102b40',color:'#acd7f5'}}>{c.replaceAll('_',' ')}</span>)}</div></div>)}</div></section>
        <section style={panel}><div style={{display:'flex',gap:8,alignItems:'center'}}><Laptop size={18}/><h2 style={{margin:0}}>Companion devices</h2></div><div style={{display:'grid',gap:9,marginTop:12}}>{(data?.devices||[]).map(d=><div key={d.id} style={{padding:12,border:'1px solid #21415a',borderRadius:10,opacity:d.status==='revoked'?.55:1}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b>{d.label}</b><div style={{fontSize:12,color:'#86a4ba',marginTop:3}}>{d.platform} · {principalName(d.principalId)} · {d.status}</div><div style={{fontSize:11,color:d.online?'#78e1b5':'#d7b77b',marginTop:4,display:'flex',gap:5,alignItems:'center'}}>{d.online?<Wifi size={13}/>:<WifiOff size={13}/>} {d.online?'online':'offline'}{d.lastSeenAt?` · seen ${new Date(d.lastSeenAt).toLocaleTimeString()}`:''}</div></div>{d.status==='active'&&<button style={button} onClick={()=>void revokeDevice(d.id)} disabled={busy===`device-${d.id}`}>Revoke</button>}</div><div style={{fontSize:11,color:'#7495ae',marginTop:7}}>Allowed local commands: {d.allowedCommands.join(', ')||'status only'}</div></div>)}{!(data?.devices||[]).length&&<div style={{color:'#7f9ab0'}}>No enrolled companion devices yet.</div>}</div></section>
        <section style={panel}><h2 style={{marginTop:0}}>Authority audit</h2>{(data?.audit||[]).slice(0,20).map(a=><div key={a.id} style={{padding:'8px 0',borderBottom:'1px solid #183149',fontSize:12}}><b>{a.action}</b>{a.target?` · ${a.target}`:''}<div style={{color:'#7897ae',marginTop:2}}>{new Date(a.createdAt).toLocaleString()}{a.detail?` · ${a.detail}`:''}</div></div>)}</section>
      </div>
      <aside style={{display:'grid',gap:14,position:'sticky',top:12}}>
        <section style={panel}><div style={{display:'flex',gap:8,alignItems:'center'}}><UserPlus size={18}/><b>Add principal</b></div><div style={{display:'grid',gap:8,marginTop:10}}><input style={input} placeholder="Name or role label" value={name} onChange={e=>setName(e.target.value)}/><select style={input} value={role} onChange={e=>setRole(e.target.value as Role)}><option value="executive">Executive</option><option value="assistant">Assistant</option><option value="operator">Operator</option><option value="viewer">Viewer</option></select><button style={button} onClick={()=>void create()} disabled={!name||busy==='create'}><UserPlus size={14}/> Create principal</button></div><p style={{fontSize:11,color:'#829eb5',lineHeight:1.5}}>Roles are capability ceilings. A delegated principal cannot exceed the permissions defined by its role, and only the bootstrap owner can manage authority.</p></section>
        {enrollment&&<section style={{...panel,borderColor:'#426c50'}}><div style={{display:'flex',gap:8,alignItems:'center'}}><KeyRound size={18}/><b>One-time enrollment</b></div><p style={{fontSize:12,color:'#a9c8b4'}}>For {enrollment.principal}. Expires {new Date(enrollment.expiresAt).toLocaleTimeString()}.</p><textarea readOnly value={enrollment.token} style={{...input,minHeight:130,fontFamily:'monospace',fontSize:10,resize:'vertical'}}/><button style={{...button,marginTop:8}} onClick={()=>void copyToken()}><Copy size={14}/> Copy enrollment token</button><p style={{fontSize:11,color:'#829eb5',lineHeight:1.5}}>On the device, set this once as <code>ELP_COMPANION_ENROLLMENT_TOKEN</code> and run the ELP companion agent. The agent exchanges it for a revocable signed device token stored locally with restricted file permissions.</p></section>}
        <section style={panel}><h3 style={{marginTop:0}}>Trust model</h3><p style={{fontSize:12,color:'#91aabd',lineHeight:1.6}}>External write/high-risk approvals are now bound to the approving principal. Companion commands are scoped to a specific enrolled device and allowlist. Revoking a principal or device invalidates future authority checks without deleting the audit trail.</p></section>
      </aside>
    </section>
  </div></main>;
}
