'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';

type Agent={id:string;name:string;domain:string;mission:string;skills:string[]};
type Mission={objective:string;generatedAt:string;synthesis:string;findings:Array<{agentId:string;agentName:string;domain:string;output:string}>;skillCandidates:Array<{name:string;purpose:string;domain:string;inputs:string[];outputs:string[];connectors:string[];validation:string[]}>};

export default function SeriousModePage(){
 const [agents,setAgents]=useState<Agent[]>([]); const [objective,setObjective]=useState(''); const [context,setContext]=useState(''); const [mission,setMission]=useState<Mission|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{void fetch('/api/identity',{method:'POST'}).then(()=>fetch('/api/serious-mode')).then(r=>r.json()).then(j=>setAgents(j.agents||[])).catch(()=>{});},[]);
 async function run(){if(!objective.trim())return;setBusy(true);setError('');setMission(null);try{const r=await fetch('/api/serious-mode',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({objective,context,maxAgents:7})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Mission failed.');setMission(j);}catch(e){setError(e instanceof Error?e.message:'Mission failed.');}finally{setBusy(false);}}
 return <main style={{minHeight:'100vh',background:'#05090e',color:'#eef4f8',padding:24,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1320,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',marginBottom:28}}><div><div style={{fontSize:12,letterSpacing:3,color:'#a5b2bc'}}>ELP GPT</div><h1 style={{fontSize:42,margin:'5px 0'}}>Serious Mode</h1><p style={{maxWidth:760,color:'#aeb9c2',lineHeight:1.55}}>Give ELP one ambitious objective. A specialist AI team attacks it in parallel, challenges assumptions, synthesizes a step-by-step execution plan, and identifies new reusable capabilities that should become skills.</p></div><Link href="/" style={{color:'#d9e2e8'}}>Exit</Link></header>
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) minmax(300px,.6fr)',gap:18}}><div style={{border:'1px solid #26323b',borderRadius:18,padding:20,background:'#0a1016'}}><label style={{fontSize:12,color:'#9eabb5'}}>WHAT DO YOU WANT TO ACCOMPLISH?</label><textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Example: Build a growth engine that gets 100 qualified customers..." style={{width:'100%',minHeight:120,marginTop:9,padding:14,borderRadius:12,border:'1px solid #33414b',background:'#070c11',color:'#fff',fontSize:17,boxSizing:'border-box'}}/><label style={{display:'block',fontSize:12,color:'#9eabb5',marginTop:16}}>OPTIONAL CONTEXT / CONSTRAINTS</label><textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Budget, deadline, existing assets, constraints, evidence..." style={{width:'100%',minHeight:90,marginTop:9,padding:14,borderRadius:12,border:'1px solid #33414b',background:'#070c11',color:'#fff',boxSizing:'border-box'}}/><button onClick={()=>void run()} disabled={busy||!objective.trim()} style={{marginTop:16,border:0,borderRadius:999,padding:'13px 22px',fontWeight:800,cursor:'pointer'}}>{busy?'Agents are working…':'Start Serious Mode'}</button>{error&&<p style={{color:'#ff9eaa'}}>{error}</p>}</div>
  <aside style={{border:'1px solid #26323b',borderRadius:18,padding:18,background:'#0a1016'}}><div style={{fontSize:12,letterSpacing:2,color:'#9eabb5'}}>AI TEAM · {agents.length}</div>{agents.map(a=><div key={a.id} style={{padding:'11px 0',borderBottom:'1px solid #1c252c'}}><b>{a.name}</b><div style={{fontSize:12,color:'#8fa0ac',marginTop:3}}>{a.domain} · {a.skills.slice(0,3).join(' · ')}</div></div>)}</aside></section>
  {mission&&<section style={{marginTop:22}}><div style={{border:'1px solid #34434d',borderRadius:18,padding:22,background:'#0a1016'}}><div style={{fontSize:12,letterSpacing:2,color:'#9eabb5'}}>INTEGRATED PLAN</div><div style={{whiteSpace:'pre-wrap',lineHeight:1.65,marginTop:12}}>{mission.synthesis}</div></div><h2 style={{marginTop:24}}>Specialist findings</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12}}>{mission.findings.map(f=><article key={f.agentId} style={{border:'1px solid #26323b',borderRadius:14,padding:16,background:'#091016'}}><b>{f.agentName}</b><div style={{fontSize:12,color:'#8fa0ac',margin:'4px 0 10px'}}>{f.domain}</div><div style={{whiteSpace:'pre-wrap',lineHeight:1.5,fontSize:14}}>{f.output}</div></article>)}</div>{mission.skillCandidates.length>0&&<><h2 style={{marginTop:24}}>Proposed new skills</h2><p style={{color:'#9eabb5'}}>These are proposals, not silently installed capabilities. Validate them before promotion.</p>{mission.skillCandidates.map(s=><article key={s.name} style={{border:'1px solid #3b4650',borderRadius:12,padding:14,marginBottom:10}}><b>{s.name}</b><div style={{color:'#aab6bf',marginTop:5}}>{s.purpose}</div><div style={{fontSize:12,marginTop:7}}>Domain: {s.domain} · Connectors: {s.connectors?.join(', ')||'none'}</div></article>)}</>}</section>}
 </div></main>;
}
