'use client';

import { useCallback, useEffect, useState } from 'react';

type Item = { id:string; source:string; title:string; horizon:'now'|'today'|'week'; score:number; priority:string; owner?:string; blocked:boolean; approvalRequired:boolean; reasons:string[]; recommendedAction:string };
type Plan = { generatedAt:string; timezone:string; capacityStatus:string; headline:string; focus:Item[]; now:Item[]; today:Item[]; week:Item[]; defer:Item[]; stopDoing:Item[]; blockers:Item[]; stats:{ totalCandidates:number; critical:number; blocked:number; decisions:number; relationshipItems:number; overload:boolean } };

function Section({ title, items }: { title:string; items:Item[] }) {
  return <section className="rounded-2xl border border-slate-800 bg-slate-950/60 p-5"><h2 className="mb-4 text-lg font-semibold text-white">{title}</h2><div className="space-y-3">{items.length ? items.map((item)=><div key={item.id} className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-sky-300">{item.source}</span><span className="rounded-full bg-slate-800 px-2 py-1 text-xs text-slate-200">Score {item.score}</span><span className="rounded-full bg-slate-800 px-2 py-1 text-xs text-slate-200">{item.priority}</span>{item.blocked&&<span className="rounded-full bg-rose-950 px-2 py-1 text-xs text-rose-200">blocked</span>}{item.approvalRequired&&<span className="rounded-full bg-amber-950 px-2 py-1 text-xs text-amber-200">decision</span>}</div><h3 className="mt-2 font-medium text-white">{item.title}</h3><p className="mt-2 text-sm text-slate-300">{item.recommendedAction}</p><p className="mt-2 text-xs text-slate-500">{item.reasons.join(' ')}</p></div>) : <p className="text-sm text-slate-500">No items.</p>}</div></section>;
}

export default function DailyPlanPage() {
  const [plan,setPlan]=useState<Plan|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/daily-plan',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Load failed');setPlan(d.plan||null);}catch(e){setError(e instanceof Error?e.message:'Load failed');}finally{setLoading(false);}},[]);
  const refresh=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/daily-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Refresh failed');setPlan(d.plan);}catch(e){setError(e instanceof Error?e.message:'Refresh failed');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[load]);
  return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium uppercase tracking-[0.22em] text-sky-400">ELP Executive Control</p><h1 className="mt-2 text-3xl font-semibold text-white">Daily Operating Plan</h1><p className="mt-2 max-w-3xl text-slate-400">A continuously re-ranked execution view across goals, commitments, work queues, capacity, delegation, relationships and forecast risk.</p></div><button onClick={refresh} disabled={loading} className="rounded-xl bg-white px-4 py-2 font-medium text-slate-950 disabled:opacity-50">{loading?'Refreshing…':'Re-rank now'}</button></div>{error&&<div className="mt-5 rounded-xl border border-rose-900 bg-rose-950/40 p-4 text-rose-200">{error}</div>}{plan&&<><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[['Capacity',plan.capacityStatus],['Candidates',plan.stats.totalCandidates],['Critical',plan.stats.critical],['Blocked',plan.stats.blocked],['Decisions',plan.stats.decisions],['Relationships',plan.stats.relationshipItems]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold text-white">{String(value)}</p></div>)}</div><div className="mt-5 rounded-2xl border border-sky-900 bg-sky-950/30 p-5"><p className="text-sm text-sky-300">Current operating headline</p><p className="mt-2 text-xl font-medium text-white">{plan.headline}</p><p className="mt-2 text-xs text-slate-500">Generated {new Date(plan.generatedAt).toLocaleString()} · {plan.timezone}</p></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Section title="Focus" items={plan.focus}/><Section title="Blocking decisions & exceptions" items={plan.blockers}/><Section title="Now" items={plan.now}/><Section title="Today" items={plan.today}/><Section title="This week" items={plan.week}/><Section title="Candidates to defer" items={plan.defer}/>{plan.stopDoing.length>0&&<Section title="Stop / pause candidates" items={plan.stopDoing}/>}</div><div className="mt-6 rounded-xl border border-slate-800 p-4 text-sm text-slate-400">Priority ranking is advisory. ELP does not silently cancel, defer, delegate, send, schedule or stop external work; consequential changes remain behind the configured approval boundary.</div></>}</div></main>;
}
