'use client';

import { useEffect, useState } from 'react';

type Decision = { disposition: 'interrupt_now' | 'queue_after_block' | 'monitor'; reason: string; margin: number; threshold: number; candidate: { id: string; title: string; summary: string; severity: string; score: number; approvalRequired: boolean; recommendedAction?: string } };
type Snapshot = { generatedAt: string; currentBlockTitle?: string; decisions: Decision[]; checkpoint?: { title: string; remainingMinutes: number; reason: string }; replanned: boolean; stats: { candidates: number; interruptNow: number; queued: number; monitored: number } };

export default function InterruptManagerPage() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const r = await fetch('/api/interrupt-manager', { cache: 'no-store' }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to load interrupt manager.'); setSnapshot(data.snapshot); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load.'); } finally { setLoading(false); } };
  const refresh = async () => { setLoading(true); setError(''); try { const r = await fetch('/api/interrupt-manager', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'refresh' }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to analyse interruptions.'); setSnapshot(data.snapshot); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to refresh.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const label = (value: Decision['disposition']) => value === 'interrupt_now' ? 'INTERRUPT NOW' : value === 'queue_after_block' ? 'QUEUE AFTER BLOCK' : 'MONITOR';
  return <main style={{ minHeight: '100vh', background: '#07111f', color: '#eef5ff', padding: 28, fontFamily: 'Inter, system-ui, sans-serif' }}><div style={{ maxWidth: 1120, margin: '0 auto' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'center', marginBottom: 24 }}><div><div style={{ fontSize: 13, letterSpacing: 2, color: '#7dd3fc' }}>ELP ADAPTIVE EXECUTION</div><h1 style={{ margin: '6px 0', fontSize: 36 }}>Interrupt Manager</h1><p style={{ margin: 0, color: '#9fb3c8' }}>Protect focus by interrupting only when a new exception materially outranks the work already in progress.</p></div><button onClick={refresh} disabled={loading} style={{ padding: '11px 16px', borderRadius: 10, border: '1px solid #26445f', background: '#10283b', color: '#fff' }}>{loading ? 'Analysing…' : 'Analyse now'}</button></div>
    {error && <div style={{ padding: 14, border: '1px solid #7f1d1d', borderRadius: 10, marginBottom: 18 }}>{error}</div>}
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: 12, marginBottom: 22 }}>{[['Candidates', snapshot?.stats.candidates || 0], ['Interrupt now', snapshot?.stats.interruptNow || 0], ['Queued', snapshot?.stats.queued || 0], ['Monitored', snapshot?.stats.monitored || 0]].map(([k,v]) => <div key={String(k)} style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 16 }}><div style={{ color: '#8da8bf', fontSize: 12 }}>{k}</div><div style={{ fontSize: 30, marginTop: 4 }}>{String(v)}</div></div>)}</section>
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 22 }}><div style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><div style={{ color: '#7dd3fc', fontSize: 12 }}>PROTECTED WORK</div><h2>{snapshot?.currentBlockTitle || 'No active focus block'}</h2><div style={{ color: '#9fb3c8' }}>{snapshot?.replanned ? 'Remaining execution plan was rebuilt after a material exception.' : 'Current work remains protected unless the interruption threshold is crossed.'}</div></div><div style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><div style={{ color: '#7dd3fc', fontSize: 12 }}>RESUME CHECKPOINT</div><h3>{snapshot?.checkpoint?.title || 'No interrupted work'}</h3><div style={{ color: '#9fb3c8' }}>{snapshot?.checkpoint ? `${snapshot.checkpoint.remainingMinutes} min preserved · ${snapshot.checkpoint.reason}` : 'When ELP interrupts a block, the remaining work is checkpointed here.'}</div></div></section>
    <section style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><h2 style={{ marginTop: 0 }}>Exception decisions</h2><div style={{ display: 'grid', gap: 10 }}>{(snapshot?.decisions || []).map((item) => <div key={item.candidate.id} style={{ background: '#0a1724', borderRadius: 10, padding: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><strong>{item.candidate.title}</strong><span style={{ color: item.disposition === 'interrupt_now' ? '#fca5a5' : '#7dd3fc', fontSize: 12 }}>{label(item.disposition)}</span></div><div style={{ color: '#9fb3c8', marginTop: 6 }}>{item.candidate.summary}</div><div style={{ color: '#7890a6', fontSize: 12, marginTop: 8 }}>score {item.candidate.score} · margin {item.margin} · threshold {item.threshold} · {item.reason}</div>{item.candidate.recommendedAction && <div style={{ marginTop: 8 }}>{item.candidate.recommendedAction}</div>}</div>)}{!snapshot?.decisions?.length && <div style={{ color: '#9fb3c8' }}>No material interruptions are currently competing with the execution plan.</div>}</div></section>
  </div></main>;
}
