'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Copy, KeyRound, LogOut, RefreshCw, ShieldCheck, UserRoundCheck, XCircle } from 'lucide-react';

type Principal={id:string;displayName:string;role:string;status:string;capabilities:string[]};
type Session={id:string;principalId:string;assurance:'standard'|'step_up';status:'active'|'revoked';createdAt:string;expiresAt:string;lastSeenAt?:string;clientFingerprint?:string};
type AuthoritySnapshot={principals:Principal[];sessions?:Session[]};
type SessionPayload={principal:Principal;delegated:boolean;currentSessionId:string|null;sessions:Session[]};
const panel:React.CSSProperties={background:'#091725',border:'1px solid #1d3c56',borderRadius:14,padding:16};
const button:React.CSSProperties={background:'#10273a',border:'1px solid #315676',borderRadius:9,color:'#e9f5ff',padding:'9px 12px',cursor:'pointer',display:'inline-flex',gap:7,alignItems:'center'};
const input:React.CSSProperties={background:'#06111f',border:'1px solid #294863',borderRadius:8,color:'#e9f5ff',padding:'10px 11px',width:'100%'};

export default function AuthoritySessionsPage(){
  const [authority,setAuthority]=useState<AuthoritySnapshot|null>(null);const [sessions,setSessions]=useState<SessionPayload|null>(null);const [token,setToken]=useState('');const [issued,setIssued]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
  const load=useCallback(async()=>{setBusy('load');setError('');try{await fetch('/api/identity',{method:'POST',cache:'no-store'});const sr=await fetch('/api/authority-session',{cache:'no-store'});const sj=await sr.json();if(!sr.ok)throw new Error(sj.error||'Could not load sessions.');setSessions(sj);const ar=await fetch('/api/authority-control',{cache:'no-store'});if(ar.ok)setAuthority(await ar.json());else setAuthority(null);}catch(e){setError(e instanceof Error?e.message:'Could not load sessions.');}finally{setBusy('');}},[]);
  useEffect(()=>{void load();},[load]);
  async function exchange(){setBusy('exchange');setError('');try{const r=await fetch('/api/authority-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'exchange-access',accessToken:token.trim()})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Access exchange failed.');setToken('');setMessage(`Delegated session active as ${j.principal.displayName}.`);await load();}catch(e){setError(e instanceof Error?e.message:'Access exchange failed.');}finally{setBusy('');}}
  async function issue(principalId:string){setBusy(`issue-${principalId}`);setError('');try{const r=await fetch('/api/authority-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create-access',principalId})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not issue access.');setIssued(j.access.token);setMessage('One-time principal access grant issued. It can establish one revocable delegated session.');}catch(e){setError(e instanceof Error?e.message:'Could not issue access.');}finally{setBusy('');}}
  async function revoke(sessionId:string){setBusy(`revoke-${sessionId}`);setError('');try{const r=await fetch('/api/authority-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:sessionId===sessions?.currentSessionId?'revoke-current':'revoke-session',sessionId})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not revoke session.');setMessage('Session revoked. Its signed cookie can no longer authorize requests.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not revoke session.');}finally{setBusy('');}}
  async function copy(value:string){await navigator.clipboard.writeText(value);setMessage('Token copied.');}
  const principalName=(id:string)=>authority?.principals.find(p=>p.id===id)?.displayName||sessions?.principal.id===id?sessions?.principal.displayName:id;
  return <main style={{minHeight:'100vh',background:'#06111f',color:'#edf7ff',padding:22,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1280,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginBottom:18}}><div><Link href="/authority-control" style={{color:'#9ecbff',textDecoration:'none',display:'flex',gap:7,alignItems:'center'}}><ArrowLeft size={17}/> Authority Control</Link><div style={{fontSize:11,letterSpacing:2,color:'#75a9d6',marginTop:14}}>ELP ZERO-TRUST SESSION PLANE</div><h1 style={{margin:'5px 0',fontSize:34}}>Principal Sessions</h1><p style={{margin:0,color:'#91aabd'}}>Issue one-time access, establish delegated sessions, and revoke them immediately without changing the principal record.</p></div><button style={button} onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></header>
    {error&&<div style={{padding:12,border:'1px solid #78384a',background:'#2a1119',borderRadius:10,color:'#ffd7df',marginBottom:12}}>{error}</div>}{message&&<div style={{padding:12,border:'1px solid #2e6b53',background:'#0a281e',borderRadius:10,color:'#baf5da',marginBottom:12}}>{message}</div>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12,marginBottom:14}}><div style={panel}><ShieldCheck size={20}/><div style={{fontSize:12,color:'#8ba7bd',marginTop:8}}>CURRENT PRINCIPAL</div><div style={{fontSize:22,fontWeight:800,marginTop:4}}>{sessions?.principal.displayName||'—'}</div><div style={{fontSize:12,color:'#8ba7bd'}}>{sessions?.principal.role||''} · {sessions?.delegated?'delegated session':'owner fallback'}</div></div><div style={panel}><UserRoundCheck size={20}/><div style={{fontSize:12,color:'#8ba7bd',marginTop:8}}>ACTIVE SESSIONS</div><div style={{fontSize:28,fontWeight:800,marginTop:4}}>{sessions?.sessions.filter(s=>s.status==='active').length||0}</div></div></section>
    <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.2fr) minmax(300px,.8fr)',gap:14,alignItems:'start'}}><div style={{display:'grid',gap:14}}><section style={panel}><h2 style={{marginTop:0}}>Session registry</h2>{(sessions?.sessions||[]).map(s=><div key={s.id} style={{padding:'11px 0',borderBottom:'1px solid #183149',display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',opacity:s.status==='revoked'?.55:1}}><div><b>{principalName(s.principalId)}</b><div style={{fontSize:11,color:'#829eb5',marginTop:3}}>{s.assurance} · {s.status} · created {new Date(s.createdAt).toLocaleString()}</div><div style={{fontSize:11,color:'#6f8ca4'}}>expires {new Date(s.expiresAt).toLocaleString()}{s.lastSeenAt?` · seen ${new Date(s.lastSeenAt).toLocaleTimeString()}`:''}</div></div>{s.status==='active'&&<button style={button} onClick={()=>void revoke(s.id)} disabled={busy===`revoke-${s.id}`}><XCircle size={14}/> Revoke</button>}</div>)}{!(sessions?.sessions||[]).length&&<p style={{color:'#829eb5'}}>No delegated sessions.</p>}</section>
      {authority&&<section style={panel}><h2 style={{marginTop:0}}>Issue delegated access</h2><p style={{fontSize:12,color:'#91aabd'}}>Each grant is single-use. After exchange, the resulting session is independently revocable.</p><div style={{display:'grid',gap:8}}>{authority.principals.filter(p=>p.status==='active'&&p.role!=='owner').map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',padding:10,border:'1px solid #1b3850',borderRadius:9}}><span><b>{p.displayName}</b><small style={{display:'block',color:'#7897ae'}}>{p.role}</small></span><button style={button} onClick={()=>void issue(p.id)}><KeyRound size={14}/> Issue access</button></div>)}</div>{issued&&<div style={{marginTop:12}}><textarea readOnly value={issued} style={{...input,minHeight:120,fontFamily:'monospace',fontSize:10}}/><button style={{...button,marginTop:7}} onClick={()=>void copy(issued)}><Copy size={14}/> Copy grant</button></div>}</section>}
    </div><aside style={{display:'grid',gap:14}}><section style={panel}><h2 style={{marginTop:0}}>Enter delegated session</h2><textarea value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste one-time principal access grant" style={{...input,minHeight:130,fontFamily:'monospace',fontSize:10}}/><button style={{...button,marginTop:8}} disabled={!token.trim()||busy==='exchange'} onClick={()=>void exchange()}><KeyRound size={14}/> Exchange access</button></section>{sessions?.delegated&&sessions.currentSessionId&&<section style={panel}><h3 style={{marginTop:0}}>Current delegated session</h3><p style={{fontSize:12,color:'#91aabd'}}>Revocation invalidates this browser's authority cookie immediately at the server registry.</p><button style={button} onClick={()=>void revoke(sessions.currentSessionId!)}><LogOut size={14}/> Revoke and exit</button></section>}</aside></section>
  </div></main>;
}
