import { createHmac, timingSafeEqual } from 'node:crypto';
import { NextResponse } from 'next/server';
import { recordInboundEvent } from '@/lib/event-fabric';
import { runInterruptManager } from '@/lib/interrupt-manager';
import { refreshNotifications } from '@/lib/notifications';
import { getOwnerProfileId } from '@/lib/owner';
export const runtime='nodejs'; export const maxDuration=60;
function verify(raw:string,timestamp:string,signature:string,secret:string){const ts=Number(timestamp);if(!Number.isFinite(ts)||Math.abs(Date.now()/1000-ts)>300)return false;const expected=`v0=${createHmac('sha256',secret).update(`v0:${timestamp}:${raw}`).digest('hex')}`;const a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}
export async function POST(request:Request){const secret=process.env.ELP_SLACK_SIGNING_SECRET?.trim();if(!secret)return NextResponse.json({error:'Slack native ingress is not configured.'},{status:503});const raw=await request.text();if(!verify(raw,request.headers.get('x-slack-request-timestamp')||'',request.headers.get('x-slack-signature')||'',secret))return NextResponse.json({error:'Invalid Slack signature.'},{status:401});let payload:Record<string,unknown>;try{payload=JSON.parse(raw) as Record<string,unknown>;}catch{return NextResponse.json({error:'Invalid payload.'},{status:400});}if(payload.type==='url_verification'&&typeof payload.challenge==='string')return NextResponse.json({challenge:payload.challenge});const profileId=getOwnerProfileId();if(!profileId)return NextResponse.json({error:'ELP owner profile unavailable.'},{status:503});const event=payload.event&&typeof payload.event==='object'?payload.event as Record<string,unknown>:{};const eventId=typeof payload.event_id==='string'?payload.event_id:undefined;const type=typeof event.type==='string'?event.type:'event';const text=typeof event.text==='string'?event.text.slice(0,1200):'';await recordInboundEvent(profileId,{provider:'slack',type:`native_${type}`,sourceId:eventId,summary:text||`Slack ${type} event received.`,metadata:{channel:typeof event.channel==='string'?event.channel:'',user:typeof event.user==='string'?event.user:'',teamId:typeof payload.team_id==='string'?payload.team_id:''}});void Promise.all([refreshNotifications(profileId),runInterruptManager({profileId,persist:true})]).catch(()=>undefined);return NextResponse.json({ok:true});}
