'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, ChevronRight, Flag, LoaderCircle, RefreshCw, Target, Users } from 'lucide-react';

type Goal = { id:string; title:string; description?:string; level:'vision'|'objective'|'key_result'; parentId?:string; owner:string; status:string; priority:string; dueDate?:string; metric?:string; target?:number; current?:number; unit?:string; taskIds:string[]; ledgerIds:string[] };
type Delegation = { id:string; taskId:string; goalId?:string; delegatee:string; channel?:string; status:string; expectedOutcome:string; dueDate?:string; checkInEveryHours:number; lastCheckInAt?:string; progress:number; blockers:string[]; evidence:string[] };
type GoalHealth = { goal:Goal; health:'healthy'|'watch'|'at_risk'|'critical'; progress:number; openTasks:number; blockedTasks:number; delegatedOpen:number; delegatedStale:number; dueInDays:number|null; reasons:string[] };
type Snapshot = { goals:Goal[]; delegations:Delegation[]; goalHealth:GoalHealth[]; delegationExceptions:Array<{delegation:Delegation;severity:'critical'|'high'|'normal';reason:string;recommendedAction:string}>; stats:{activeGoals:number;criticalGoals:number;atRiskGoals:number;delegatedOpen:number;delegationExceptions:number;orphanTasks:number} };
type Task={id:string;title:string;queue:string;status:string;priority:string};
const card={border:'1px solid #1d3b57',background:'#091827',borderRadius:16,padding:16} as const;
const button={border:'1px solid #315572',background:'#0b1d2e',color:'#dceeff',borderRadius:999,padding:'8px 12px',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:6} as const;
const input={background:'#071421',border:'1px solid #294963',color:'#eaf4ff',borderRadius:9,padding:'9px 10px',width:'100%'} as const;

export default function PortfolioControlPage(){
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [tasks,setTasks]=useState<Task[]>([]); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [goal,setGoal]=useState({title:'',description:'',level:'objective',parentId:'',priority:'normal',dueDate:'',metric:'',target:'',unit:''});
  const [deleg,setDeleg]=useState({taskId:'',goalId:'',delegatee:'',channel:'email',expectedOutcome:'',dueDate:'',checkInEveryHours:'48'});
  useEffect(()=>{void fetch('/api/identity',{method:'POST'}).then(()=>load()).catch(()=>load());},[]);
  async function load(){setBusy('load');setError('');try{const [p,t]=await Promise.all([fetch('/api/portfolio-control',{cache:'no-store'}),fetch('/api/tasks',{cache:'no-store'})]);const pj=await p.json();const tj=await t.json();if(!p.ok)throw new Error(pj.error||'Portfolio load failed.');setSnapshot(pj);setTasks(Object.values(tj.queues||{}).flat() as Task[]);}catch(e){setError(e instanceof Error?e.message:'Portfolio load failed.');}finally{setBusy('');}}
  async function post(body:Record<string,unknown>){setBusy('post');setError('');try{const r=await fetch('/api/portfolio-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Portfolio action failed.');await load();return j;}catch(e){setError(e instanceof Error?e.message:'Portfolio action failed.');}finally{setBusy('');}}
  async function createGoal(){if(!goal.title.trim())return;await post({action:'create-goal',title:goal.title,description:goal.description||undefined,level:goal.level,parentId:goal.parentId||undefined,priority:goal.priority,dueDate:goal.dueDate||undefined,metric:goal.metric||undefined,target:goal.target?Number(goal.target):undefined,unit:goal.unit||undefined,owner:'user'});setGoal({title:'',description:'',level:'objective',parentId:'',priority:'normal',dueDate:'',metric:'',target:'',unit:''});setMessage('Goal created in hierarchy.');}
  async function createDelegation(){if(!deleg.taskId||!deleg.delegatee||!deleg.expectedOutcome)return;await post({action:'create-delegation',taskId:deleg.taskId,goalId:deleg.goalId||undefined,delegatee:deleg.delegatee,channel:deleg.channel,expectedOutcome:deleg.expectedOutcome,dueDate:deleg.dueDate||undefined,checkInEveryHours:Number(deleg.checkInEveryHours)||48});setDeleg({taskId:'',goalId:'',delegatee:'',channel:'email',expectedOutcome:'',dueDate:'',checkInEveryHours:'48'});setMessage('Delegation created and now tracked for evidence, cadence and blockers.');}
  async function linkTask(goal:Goal,taskId:string){if(!taskId)return;await post({action:'update-goal',goalId:goal.id,taskIds:[...new Set([...goal.taskIds,taskId])]});}
  const byParent=useMemo(()=>{const m=new Map<string,Goal[]>();for(const g of snapshot?.goals||[]){const k=g.parentId||'root';m.set(k,[...(m.get(k)||[]),g]);}return m;},[snapshot]);
  const healthById=useMemo(()=>new Map((snapshot?.goalHealth||[]).map(h=>[h.goal.id,h])),[snapshot]);
  function GoalNode({goal,depth=0}:{goal:Goal;depth?:number}){const h=healthById.get(goal.id);const children=byParent.get(goal.id)||[];return <div style={{marginLeft:depth?18:0,marginTop:10}}><div style={{...card,padding:13,borderColor:h?.health==='critical'?'#6d3340':h?.health==='at_risk'?'#725c2b':'#1d3b57'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><div style={{fontSize:10,color:'#73a6d2'}}>{goal.level.toUpperCase().replace('_',' ')} · {goal.priority.toUpperCase()}</div><h3 style={{margin:'5px 0'}}>{goal.title}</h3><div style={{fontSize:11,color:'#859fb6'}}>{h?.health||goal.status} · {h?.progress??0}%{goal.dueDate?` · due ${goal.dueDate}`:''}</div></div><select value={goal.status} onChange={e=>void post({action:'update-goal',goalId:goal.id,status:e.target.value})} style={{...input,width:130}}><option value="active">Active</option><option value="at_risk">At risk</option><option value="achieved">Achieved</option><option value="paused">Paused</option><option value="cancelled">Cancelled</option></select></div>{goal.description&&<p style={{fontSize:12,color:'#bfd2e2'}}>{goal.description}</p>}<div style={{fontSize:11,color:'#93aabd'}}>{(h?.reasons||[]).join(' ')}</div><div style={{display:'flex',gap:7,marginTop:9,flexWrap:'wrap'}}><select defaultValue="" onChange={e=>{void linkTask(goal,e.target.value);e.currentTarget.value='';}} style={{...input,width:210}}><option value="">Link execution task…</option>{tasks.filter(t=>!goal.taskIds.includes(t.id)&&!['completed','cancelled'].includes(t.status)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select>{goal.taskIds.slice(0,4).map(id=><span key={id} style={{fontSize:10,border:'1px solid #315572',padding:'5px 7px',borderRadius:999}}>task:{id.slice(0,6)}</span>)}</div></div>{children.map(c=><GoalNode key={c.id} goal={c} depth={depth+1}/>)}</div>}
  return <main style={{minHeight:'100vh',background:'#06111f',color:'#eaf4ff',padding:24,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1400,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:18}}><Link href="/mission-control" style={{color:'#9dc9ff',textDecoration:'none',display:'flex',gap:7,alignItems:'center'}}><ArrowLeft size={17}/> Mission Control</Link><div style={{textAlign:'center'}}><div style={{fontSize:10,letterSpacing:2,color:'#6f9dc8'}}>ELP</div><h1 style={{margin:'4px 0'}}>Portfolio Control</h1><div style={{fontSize:11,color:'#78e1b5'}}>NESTED GOALS · TASK LINKAGE · DELEGATION CRUD · EVIDENCE</div></div><button style={button} onClick={()=>void load()} disabled={busy==='load'}>{busy==='load'?<LoaderCircle size={14}/>:<RefreshCw size={14}/>} Refresh</button></header>
    {error&&<div style={{padding:12,background:'#2a1119',border:'1px solid #773247',borderRadius:10,color:'#ffd9df',marginBottom:10}}>{error}</div>}{message&&<div style={{padding:12,background:'#0a261d',border:'1px solid #28644f',borderRadius:10,color:'#bdf4dc',marginBottom:10}}>{message}</div>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(155px,1fr))',gap:9,marginBottom:14}}>{[['Active goals',snapshot?.stats.activeGoals||0,<Target key="a"/>],['Critical',snapshot?.stats.criticalGoals||0,<AlertTriangle key="b"/>],['At risk',snapshot?.stats.atRiskGoals||0,<Flag key="c"/>],['Delegated',snapshot?.stats.delegatedOpen||0,<Users key="d"/>],['Exceptions',snapshot?.stats.delegationExceptions||0,<AlertTriangle key="e"/>],['Orphan tasks',snapshot?.stats.orphanTasks||0,<Flag key="f"/>]].map(([l,v,i])=><div key={String(l)} style={card}><div style={{display:'flex',justifyContent:'space-between',fontSize:10,color:'#749fc4'}}><span>{l}</span>{i}</div><div style={{fontSize:27,fontWeight:700,marginTop:5}}>{String(v)}</div></div>)}</section>
    <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.25fr) minmax(330px,.75fr)',gap:14,alignItems:'start'}}>
      <div><div style={{fontSize:11,letterSpacing:1.3,color:'#6f9dc8'}}>GOAL HIERARCHY</div>{(byParent.get('root')||[]).length?(byParent.get('root')||[]).map(g=><GoalNode key={g.id} goal={g}/>):<div style={{...card,marginTop:10,color:'#829eb6'}}>No goals yet.</div>}
        <div style={{fontSize:11,letterSpacing:1.3,color:'#6f9dc8',marginTop:18}}>DELEGATED WORK</div>{(snapshot?.delegations||[]).map(d=><div key={d.id} style={{...card,marginTop:9}}><div style={{display:'flex',justifyContent:'space-between',gap:9,flexWrap:'wrap'}}><div><b>{d.delegatee}</b><div style={{fontSize:12,color:'#99afc1'}}>{d.expectedOutcome}</div></div><select style={{...input,width:130}} value={d.status} onChange={e=>void post({action:'update-delegation',delegationId:d.id,status:e.target.value,lastCheckInAt:new Date().toISOString()})}><option value="delegated">Delegated</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div style={{display:'flex',alignItems:'center',gap:9,marginTop:10}}><input type="range" min="0" max="100" value={d.progress} onChange={e=>void post({action:'update-delegation',delegationId:d.id,progress:Number(e.target.value),lastCheckInAt:new Date().toISOString()})} style={{flex:1}}/><span>{d.progress}%</span></div><div style={{fontSize:11,color:'#8fa8bc'}}>Task {d.taskId.slice(0,8)}{d.goalId?` · Goal ${d.goalId.slice(0,8)}`:''}{d.dueDate?` · due ${d.dueDate}`:''}</div></div>)}
        {(snapshot?.delegationExceptions||[]).length>0&&<div style={{marginTop:16}}><div style={{fontSize:11,color:'#e7bc67'}}>EXCEPTIONS</div>{snapshot!.delegationExceptions.map(x=><div key={x.delegation.id} style={{...card,marginTop:8,borderColor:'#66552a'}}><b>{x.severity.toUpperCase()} · {x.delegation.delegatee}</b><p style={{fontSize:12,color:'#ddc387'}}>{x.reason}</p><div style={{fontSize:12}}><ChevronRight size={12} style={{verticalAlign:'middle'}}/> {x.recommendedAction}</div></div>)}</div>}
      </div>
      <aside style={{display:'grid',gap:12,position:'sticky',top:12}}><section style={card}><b>Create goal</b><div style={{display:'grid',gap:7,marginTop:10}}><input style={input} placeholder="Goal title" value={goal.title} onChange={e=>setGoal({...goal,title:e.target.value})}/><textarea style={input} placeholder="Description" value={goal.description} onChange={e=>setGoal({...goal,description:e.target.value})}/><select style={input} value={goal.level} onChange={e=>setGoal({...goal,level:e.target.value})}><option value="vision">Vision</option><option value="objective">Objective</option><option value="key_result">Key result</option></select><select style={input} value={goal.parentId} onChange={e=>setGoal({...goal,parentId:e.target.value})}><option value="">No parent</option>{(snapshot?.goals||[]).map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select><select style={input} value={goal.priority} onChange={e=>setGoal({...goal,priority:e.target.value})}><option value="critical">Critical</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select><input type="date" style={input} value={goal.dueDate} onChange={e=>setGoal({...goal,dueDate:e.target.value})}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}><input style={input} placeholder="Metric" value={goal.metric} onChange={e=>setGoal({...goal,metric:e.target.value})}/><input style={input} placeholder="Target" type="number" value={goal.target} onChange={e=>setGoal({...goal,target:e.target.value})}/></div><button style={button} onClick={()=>void createGoal()} disabled={!goal.title||busy==='post'}><CheckCircle2 size={14}/> Create</button></div></section>
      <section style={card}><b>Create delegation</b><div style={{display:'grid',gap:7,marginTop:10}}><select style={input} value={deleg.taskId} onChange={e=>setDeleg({...deleg,taskId:e.target.value})}><option value="">Task…</option>{tasks.filter(t=>!['completed','cancelled'].includes(t.status)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select style={input} value={deleg.goalId} onChange={e=>setDeleg({...deleg,goalId:e.target.value})}><option value="">No goal link</option>{(snapshot?.goals||[]).map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select><input style={input} placeholder="Delegatee" value={deleg.delegatee} onChange={e=>setDeleg({...deleg,delegatee:e.target.value})}/><input style={input} placeholder="Expected outcome" value={deleg.expectedOutcome} onChange={e=>setDeleg({...deleg,expectedOutcome:e.target.value})}/><input type="date" style={input} value={deleg.dueDate} onChange={e=>setDeleg({...deleg,dueDate:e.target.value})}/><input type="number" style={input} placeholder="Check-in hours" value={deleg.checkInEveryHours} onChange={e=>setDeleg({...deleg,checkInEveryHours:e.target.value})}/><button style={button} onClick={()=>void createDelegation()} disabled={!deleg.taskId||!deleg.delegatee||!deleg.expectedOutcome||busy==='post'}><Users size={14}/> Delegate</button></div></section></aside>
    </section>
  </div></main>;
}
