import type { ElpSkill } from '@/lib/skills';

export const AGENT_PLATFORM_SKILLS = [
  {
    id: 'slashy-communications-operator',
    name: 'Slashy Communications Operator',
    category: 'communication',
    description: 'Operate across email, calendar, research and follow-ups using anchored memory, personalized drafting, dropped-ball detection and approval-gated actions.',
    risk: 'write',
    toolkits: ['GMAIL', 'OUTLOOK', 'GOOGLECALENDAR', 'COMPOSIO_SEARCH'],
    keywords: ['slashy', 'inbox agent', 'dropped balls', 'follow up', 'email assistant', 'communications operator'],
    examples: ['Find dropped balls in my inbox', 'Draft the replies that need my attention'],
    requires: ['Connected communications provider', 'Hermes reasoning provider'],
  },
  {
    id: 'anchored-memory-routing',
    name: 'Anchored Memory Routing',
    category: 'intelligence',
    description: 'Apply stable facts, person/company context and activity-specific instructions only when their anchor is relevant to the current task.',
    risk: 'read',
    toolkits: [],
    keywords: ['memory anchor', 'remember preference', 'person memory', 'company memory', 'activity memory'],
    examples: ['Use my email-writing preferences only for email', 'Remember this rule for this company'],
    requires: ['ELP memory'],
  },
  {
    id: 'dropped-ball-radar',
    name: 'Dropped-Ball Radar',
    category: 'automation',
    description: 'Detect stale commitments, unanswered high-value communications, overdue follow-ups and obligations that need action.',
    risk: 'read',
    toolkits: ['GMAIL', 'OUTLOOK', 'GOOGLECALENDAR'],
    keywords: ['dropped ball', 'overdue follow up', 'forgotten reply', 'stale commitment', 'needs attention'],
    examples: ['What have I forgotten to follow up on?', 'Scan for dropped balls'],
    requires: ['Communications sync and commitment ledger'],
  },
  {
    id: 'vellum-workflow-runtime',
    name: 'Vellum Workflow Runtime',
    category: 'automation',
    description: 'Run versioned graph workflows with typed nodes, bounded loops, tool calls, conditional edges, subflows and explicit final outputs.',
    risk: 'write',
    toolkits: ['COMPOSIO_SEARCH'],
    keywords: ['vellum', 'workflow graph', 'agent node', 'subworkflow', 'workflow runtime'],
    examples: ['Run this multi-step agent workflow', 'Build a bounded agent loop'],
    requires: ['Hermes reasoning provider'],
  },
  {
    id: 'agent-evaluation-suite',
    name: 'Agent Evaluation Suite',
    category: 'developer',
    description: 'Evaluate agent and workflow outputs across scenarios with quantitative metrics, regression gates and pass/fail thresholds.',
    risk: 'read',
    toolkits: [],
    keywords: ['agent eval', 'test suite', 'regression test', 'score prompt', 'workflow evaluation'],
    examples: ['Evaluate this agent across ten scenarios', 'Block deployment if quality regresses'],
    requires: ['Test scenarios and metrics'],
  },
  {
    id: 'agent-trace-replay',
    name: 'Agent Trace & Replay',
    category: 'developer',
    description: 'Capture node-by-node inputs, outputs, tool calls, latency, errors and costs so agent executions can be inspected and replayed.',
    risk: 'read',
    toolkits: [],
    keywords: ['agent trace', 'workflow replay', 'observability', 'latency', 'execution history'],
    examples: ['Show me why this workflow failed', 'Replay the slowest execution path'],
    requires: ['Workflow execution trace'],
  },
  {
    id: 'serious-multi-agent-mode',
    name: 'Serious Multi-Agent Mode',
    category: 'intelligence',
    description: 'Assemble a bounded cross-functional swarm of strategy, research, growth, sales, content, product, engineering, automation, finance, legal, security and operations specialists, then reconcile their evidence, disagreements, risks and execution plan.',
    risk: 'read',
    toolkits: [],
    keywords: ['serious mode', 'multi-agent', 'expert swarm', 'specialist swarm', 'cross-functional analysis', 'multi-agent strategy'],
    examples: ['Use Serious Mode to analyse this business', 'Get multiple specialists to challenge this plan'],
    requires: ['Hermes or Together reasoning provider'],
  },
] as const satisfies readonly ElpSkill[];
