import type { ElpSkill } from '@/lib/skills';

export const HERMES_CREATIVE_SKILLS = [
  {
    id: 'brand-brain',
    name: 'Brand Brain',
    category: 'intelligence',
    description: 'Build a concise operating model of a brand from its website, offers, positioning, proof, tone, visual language, constraints and prior assets.',
    risk: 'read',
    toolkits: ['COMPOSIO_SEARCH', 'GOOGLEDRIVE'],
    keywords: ['brand brain', 'brand context', 'brand strategy', 'tone of voice', 'brand assets'],
    examples: ['Learn this brand before creating the campaign', 'Build the brand brain from our website and files'],
    requires: ['Public website or authorized brand files'],
  },
  {
    id: 'competitor-ad-intelligence',
    name: 'Competitor Ad Intelligence',
    category: 'intelligence',
    description: 'Research competitor positioning, creative patterns, offers, hooks, landing pages and public advertising examples without copying protected creative.',
    risk: 'read',
    toolkits: ['COMPOSIO_SEARCH', 'METAADS'],
    keywords: ['competitor ads', 'ad library', 'competitor creative', 'creative intelligence', 'ads analysis'],
    examples: ['Analyse competitor ads before making ours', 'Find the dominant hooks in this category'],
    requires: ['Public web search and optional authorized Meta Ads connection'],
  },
  {
    id: 'creative-strategy',
    name: 'Creative Strategy',
    category: 'intelligence',
    description: 'Convert an objective, audience and evidence into campaign angles, offers, hooks, formats, visual territories and measurable hypotheses.',
    risk: 'read',
    toolkits: [],
    keywords: ['creative strategy', 'campaign angles', 'ad concepts', 'hooks', 'offers'],
    examples: ['Create five distinct campaign angles', 'Turn this brief into testable creative hypotheses'],
    requires: ['Campaign objective and audience'],
  },
  {
    id: 'performance-copy-chief',
    name: 'Performance Copy Chief',
    category: 'social',
    description: 'Write evidence-grounded ad hooks, headlines, body copy, CTA variants and platform-specific copy without inventing claims.',
    risk: 'read',
    toolkits: [],
    keywords: ['ad copy', 'headlines', 'hooks', 'cta', 'performance copy'],
    examples: ['Write five ad variants', 'Create hooks for the winning angle'],
    requires: ['Verified product and offer claims'],
  },
  {
    id: 'creative-art-direction',
    name: 'Creative Art Direction',
    category: 'social',
    description: 'Translate strategy into executable visual direction, composition, hierarchy, typography, product treatment, scene and generation prompts.',
    risk: 'read',
    toolkits: [],
    keywords: ['art direction', 'visual direction', 'creative prompt', 'image prompt', 'ad design'],
    examples: ['Turn this angle into a production-ready image brief', 'Design five visual territories'],
    requires: ['Creative strategy or campaign brief'],
  },
  {
    id: 'ai-creative-rendering',
    name: 'AI Creative Rendering',
    category: 'social',
    description: 'Render approved marketing concepts through a connected image/video generation provider such as Higgsfield or Luma.',
    risk: 'write',
    toolkits: ['HIGGSFIELD_MCP', 'LUMA_LABS'],
    keywords: ['render ad', 'generate ad', 'higgsfield', 'luma', 'create image', 'creative generation'],
    examples: ['Render five ad concepts', 'Generate the approved image variant'],
    requires: ['Connected generation provider', 'Approval or standing authority for paid generation'],
  },
  {
    id: 'creative-qa',
    name: 'Creative QA & Brand Compliance',
    category: 'social',
    description: 'Score generated creatives for objective fit, brand fidelity, legibility, unsupported claims, platform readiness and variation diversity.',
    risk: 'read',
    toolkits: [],
    keywords: ['creative qa', 'brand compliance', 'score ads', 'review creative', 'quality check'],
    examples: ['Review these five ads and rank them', 'Reject variants that violate the brand brief'],
    requires: ['Creative outputs and brand constraints'],
  },
  {
    id: 'creative-experiment-design',
    name: 'Creative Experiment Design',
    category: 'automation',
    description: 'Create a controlled test matrix for creative variables, audiences, placements, hypotheses, metrics and stopping rules.',
    risk: 'read',
    toolkits: [],
    keywords: ['ab test ads', 'creative testing', 'experiment matrix', 'winning creative', 'performance test'],
    examples: ['Design the test for these five variants', 'Define the learning agenda and stop conditions'],
    requires: ['Campaign objective and candidate creatives'],
  },
  {
    id: 'creative-publishing',
    name: 'Creative Publishing',
    category: 'social',
    description: 'Prepare and publish an approved creative to connected social channels through the existing action approval pipeline.',
    risk: 'high',
    toolkits: ['INSTAGRAM', 'METAADS'],
    keywords: ['publish ad', 'post campaign', 'instagram publish', 'launch creative', 'meta ads'],
    examples: ['Publish the approved Instagram creative', 'Prepare the winning variant for launch'],
    requires: ['Connected social account', 'Explicit approval or standing authority'],
  },
  {
    id: 'senior-hermes-executor',
    name: 'Senior Hermes Executor',
    category: 'automation',
    description: 'Own an outcome end-to-end: discover tools, build context, delegate specialist work, execute safe reads, prepare bounded writes, verify evidence and return completed deliverables or explicit blockers.',
    risk: 'write',
    toolkits: ['COMPOSIO_SEARCH', 'HIGGSFIELD_MCP', 'LUMA_LABS', 'INSTAGRAM', 'METAADS'],
    keywords: ['execute campaign', 'senior agent', 'hermes executor', 'run workflow', 'do it end to end', 'autonomous creative'],
    examples: ['Create five ads from our brand and competitor research', 'Run the full creative workflow and prepare final assets'],
    requires: ['Hermes reasoning provider', 'At least one usable research connector', 'Approval policy for external writes'],
  },
] as const satisfies readonly ElpSkill[];
