import { randomUUID, timingSafeEqual } from 'node:crypto';
import { Honcho } from '@honcho-ai/sdk';
import { listHonchoMessages } from '@/lib/honcho-pagination';

export type DeviceCommandType = 'focus_on'|'focus_off'|'open_url'|'open_app'|'lock_screen'|'screenshot'|'screen_describe'|'clipboard_read'|'clipboard_write'|'file_list'|'file_read'|'file_write'|'notify'|'browser_open'|'type_text'|'key_press'|'mouse_click'|'run_process';
export type DeviceCommandStatus='pending'|'claimed'|'completed'|'failed'|'cancelled';
export type DeviceCommand={id:string;type:DeviceCommandType;target?:string;status:DeviceCommandStatus;requestedAt:string;updatedAt:string;claimedAt?:string;completedAt?:string;result?:string;deviceId?:string;targetDeviceId?:string;requestedByPrincipalId?:string;};
export const DEVICE_COMMAND_TYPES:readonly DeviceCommandType[]=['focus_on','focus_off','open_url','open_app','lock_screen','screenshot','screen_describe','clipboard_read','clipboard_write','file_list','file_read','file_write','notify','browser_open','type_text','key_press','mouse_click','run_process'];
const TYPES=new Set<DeviceCommandType>(DEVICE_COMMAND_TYPES);
function workspaceId(){return process.env.HONCHO_WORKSPACE_ID||'elp-gpt';}
async function sessionFor(profileId:string){if(!process.env.HONCHO_API_KEY)return null;const h=new Honcho({apiKey:process.env.HONCHO_API_KEY,workspaceId:workspaceId(),environment:'production'});const user=await h.peer(`user-${profileId}`);const elp=await h.peer('elp');const session=await h.session(`device-control-${profileId}`);await session.addPeers([user,elp]);return{user,elp,session};}
function parseJsonTarget(value:string){try{const parsed=JSON.parse(value) as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();return parsed as Record<string,unknown>;}catch{throw new Error('This device command requires a JSON object target.');}}
function safeTarget(type:DeviceCommandType,value?:string){const target=(value||'').trim().slice(0,8000);if((type==='open_url'||type==='browser_open')&&target&&!/^https:\/\//i.test(target))throw new Error('Only HTTPS URLs may be opened by a device agent.');if(type==='open_app'&&target&&!/^[\w .-]{1,120}$/.test(target))throw new Error('Invalid application name.');if(['file_list','file_read','file_write','notify','mouse_click','run_process'].includes(type)&&target)parseJsonTarget(target);if(type==='clipboard_write'||type==='type_text'){if(target.length>6000)throw new Error('Text command exceeds the local-control limit.');}if(type==='key_press'&&target&&!/^[A-Za-z0-9+_-]{1,80}$/.test(target))throw new Error('Invalid key command.');return target||undefined;}
function parse(message:{id:string;createdAt:string;metadata:Record<string,unknown>}):DeviceCommand|null{const m=message.metadata||{};if(m.elpDeviceCommand!==true||!TYPES.has(String(m.commandType) as DeviceCommandType))return null;const status=['pending','claimed','completed','failed','cancelled'].includes(String(m.commandStatus))?String(m.commandStatus) as DeviceCommandStatus:'pending';return{id:typeof m.commandId==='string'?m.commandId:message.id,type:m.commandType as DeviceCommandType,target:typeof m.target==='string'&&m.target?m.target:undefined,status,requestedAt:typeof m.requestedAt==='string'?m.requestedAt:message.createdAt,updatedAt:typeof m.updatedAt==='string'?m.updatedAt:message.createdAt,claimedAt:typeof m.claimedAt==='string'?m.claimedAt:undefined,completedAt:typeof m.completedAt==='string'?m.completedAt:undefined,result:typeof m.result==='string'?m.result:undefined,deviceId:typeof m.deviceId==='string'?m.deviceId:undefined,targetDeviceId:typeof m.targetDeviceId==='string'&&m.targetDeviceId?m.targetDeviceId:undefined,requestedByPrincipalId:typeof m.requestedByPrincipalId==='string'&&m.requestedByPrincipalId?m.requestedByPrincipalId:undefined};}
export function deviceAgentConfigured(){return Boolean(process.env.ELP_DEVICE_AGENT_TOKEN?.trim());}
export function verifyDeviceAgentToken(value:string|undefined){const expected=process.env.ELP_DEVICE_AGENT_TOKEN?.trim();if(!expected||!value)return false;const a=Buffer.from(expected),b=Buffer.from(value);return a.length===b.length&&timingSafeEqual(a,b);}
export async function listDeviceCommands(profileId:string,limit=100){const h=await sessionFor(profileId);if(!h)return[] as DeviceCommand[];const messages=await listHonchoMessages(h.session,{pageSize:100,maxPages:20,reverse:true});return messages.map(parse).filter((x):x is DeviceCommand=>Boolean(x)).slice(0,limit);}
export async function enqueueDeviceCommand(profileId:string,type:DeviceCommandType,target?:string,options?:{targetDeviceId?:string;requestedByPrincipalId?:string;allowWithoutLegacyAgent?:boolean}){if(!deviceAgentConfigured()&&!options?.allowWithoutLegacyAgent)throw new Error('No local ELP device agent is connected/configured.');if(!TYPES.has(type))throw new Error('Unsupported device command.');const h=await sessionFor(profileId);if(!h)throw new Error('Device command queue is unavailable.');const now=new Date().toISOString();const targetDeviceId=options?.targetDeviceId?.trim().slice(0,96)||undefined;const requestedByPrincipalId=options?.requestedByPrincipalId?.trim().slice(0,96)||undefined;const command:DeviceCommand={id:randomUUID(),type,target:safeTarget(type,target),status:'pending',requestedAt:now,updatedAt:now,targetDeviceId,requestedByPrincipalId};const created=await h.session.addMessages([{peerId:h.user.id,content:`[DEVICE_COMMAND] ${type}`,metadata:{elpDeviceCommand:true,recordVersion:3,commandId:command.id,commandType:type,target:command.target||'',commandStatus:'pending',targetDeviceId:targetDeviceId||'',requestedByPrincipalId:requestedByPrincipalId||'',requestedAt:now,updatedAt:now}}]);return{...command,messageId:created[0]?.id};}
export async function claimPendingCommands(profileId:string,deviceId:string,allowedTypes?:readonly DeviceCommandType[]){const h=await sessionFor(profileId);if(!h)return[] as DeviceCommand[];const allow=allowedTypes?.length?new Set(allowedTypes):null;const messages=await listHonchoMessages(h.session,{pageSize:100,maxPages:10,reverse:false});const pending=messages.map((m)=>({message:m,command:parse(m)})).filter((x):x is {message:typeof messages[number];command:DeviceCommand}=>x.command!==null&&x.command.status==='pending'&&(!x.command.targetDeviceId||x.command.targetDeviceId===deviceId)&&(!allow||allow.has(x.command.type))).slice(0,10);const now=new Date().toISOString();for(const item of pending)await h.session.updateMessage(item.message.id,{...item.message.metadata,commandStatus:'claimed',deviceId:deviceId.slice(0,120),claimedAt:now,updatedAt:now});return pending.map((x)=>({...x.command,status:'claimed' as const,deviceId,claimedAt:now,updatedAt:now}));}
export async function completeDeviceCommand(profileId:string,commandId:string,deviceId:string,ok:boolean,result?:string){const h=await sessionFor(profileId);if(!h)throw new Error('Device command queue is unavailable.');const messages=await listHonchoMessages(h.session,{pageSize:100,maxPages:20,reverse:true});const message=messages.find((m)=>m.metadata?.elpDeviceCommand===true&&m.metadata?.commandId===commandId);if(!message)throw new Error('Device command not found.');if(typeof message.metadata?.deviceId==='string'&&message.metadata.deviceId&&message.metadata.deviceId!==deviceId)throw new Error('Device command belongs to a different companion.');if(typeof message.metadata?.targetDeviceId==='string'&&message.metadata.targetDeviceId&&message.metadata.targetDeviceId!==deviceId)throw new Error('Device command targets a different companion.');const now=new Date().toISOString();await h.session.updateMessage(message.id,{...message.metadata,commandStatus:ok?'completed':'failed',deviceId:deviceId.slice(0,120),completedAt:now,updatedAt:now,result:(result||'').slice(0,4000)});}
