import { randomUUID, timingSafeEqual } from 'node:crypto';
import { Honcho } from '@honcho-ai/sdk';
import { listHonchoMessages } from '@/lib/honcho-pagination';

export type DeviceCommandType = 'focus_on' | 'focus_off' | 'open_url' | 'open_app' | 'lock_screen';
export type DeviceCommandStatus = 'pending' | 'claimed' | 'completed' | 'failed' | 'cancelled';
export type DeviceCommand = { id: string; type: DeviceCommandType; target?: string; status: DeviceCommandStatus; requestedAt: string; updatedAt: string; claimedAt?: string; completedAt?: string; result?: string; deviceId?: string };
const TYPES = new Set<DeviceCommandType>(['focus_on', 'focus_off', 'open_url', 'open_app', 'lock_screen']);

function workspaceId() { return process.env.HONCHO_WORKSPACE_ID || 'elp-gpt'; }
async function sessionFor(profileId: string) { if (!process.env.HONCHO_API_KEY) return null; const honcho = new Honcho({ apiKey: process.env.HONCHO_API_KEY, workspaceId: workspaceId(), environment: 'production' }); const user = await honcho.peer(`user-${profileId}`); const elp = await honcho.peer('elp'); const session = await honcho.session(`device-control-${profileId}`); await session.addPeers([user, elp]); return { user, elp, session }; }
function safeTarget(type: DeviceCommandType, value?: string) { const target = (value || '').trim().slice(0, 500); if (type === 'open_url' && target && !/^https:\/\//i.test(target)) throw new Error('Only HTTPS URLs may be opened by a device agent.'); if (type === 'open_app' && target && !/^[\w .-]{1,120}$/.test(target)) throw new Error('Invalid application name.'); return target || undefined; }
function parse(message: { id: string; createdAt: string; metadata: Record<string, unknown> }): DeviceCommand | null { const m = message.metadata || {}; if (m.elpDeviceCommand !== true || !TYPES.has(String(m.commandType) as DeviceCommandType)) return null; const status = ['pending','claimed','completed','failed','cancelled'].includes(String(m.commandStatus)) ? String(m.commandStatus) as DeviceCommandStatus : 'pending'; return { id: typeof m.commandId === 'string' ? m.commandId : message.id, type: m.commandType as DeviceCommandType, target: typeof m.target === 'string' && m.target ? m.target : undefined, status, requestedAt: typeof m.requestedAt === 'string' ? m.requestedAt : message.createdAt, updatedAt: typeof m.updatedAt === 'string' ? m.updatedAt : message.createdAt, claimedAt: typeof m.claimedAt === 'string' ? m.claimedAt : undefined, completedAt: typeof m.completedAt === 'string' ? m.completedAt : undefined, result: typeof m.result === 'string' ? m.result : undefined, deviceId: typeof m.deviceId === 'string' ? m.deviceId : undefined }; }

export function deviceAgentConfigured() { return Boolean(process.env.ELP_DEVICE_AGENT_TOKEN?.trim()); }
export function verifyDeviceAgentToken(value: string | undefined) { const expected = process.env.ELP_DEVICE_AGENT_TOKEN?.trim(); if (!expected || !value) return false; const a = Buffer.from(expected); const b = Buffer.from(value); return a.length === b.length && timingSafeEqual(a, b); }
export async function listDeviceCommands(profileId: string, limit = 100) { const handles = await sessionFor(profileId); if (!handles) return [] as DeviceCommand[]; const messages = await listHonchoMessages(handles.session, { pageSize: 100, maxPages: 20, reverse: true }); return messages.map(parse).filter((item): item is DeviceCommand => Boolean(item)).slice(0, limit); }
export async function enqueueDeviceCommand(profileId: string, type: DeviceCommandType, target?: string) { if (!deviceAgentConfigured()) throw new Error('No local ELP device agent is connected/configured.'); if (!TYPES.has(type)) throw new Error('Unsupported device command.'); const handles = await sessionFor(profileId); if (!handles) throw new Error('Device command queue is unavailable.'); const now = new Date().toISOString(); const command: DeviceCommand = { id: randomUUID(), type, target: safeTarget(type, target), status: 'pending', requestedAt: now, updatedAt: now }; const created = await handles.session.addMessages([{ peerId: handles.user.id, content: `[DEVICE_COMMAND] ${type}`, metadata: { elpDeviceCommand: true, recordVersion: 1, commandId: command.id, commandType: type, target: command.target || '', commandStatus: 'pending', requestedAt: now, updatedAt: now } }]); return { ...command, messageId: created[0]?.id }; }
export async function claimPendingCommands(profileId: string, deviceId: string) { const handles = await sessionFor(profileId); if (!handles) return [] as DeviceCommand[]; const messages = await listHonchoMessages(handles.session, { pageSize: 100, maxPages: 10, reverse: false }); const pending = messages.map((m) => ({ message: m, command: parse(m) })).filter((x): x is { message: typeof messages[number]; command: DeviceCommand } => x.command !== null && x.command.status === 'pending').slice(0, 10); const now = new Date().toISOString(); for (const item of pending) await handles.session.updateMessage(item.message.id, { ...item.message.metadata, commandStatus: 'claimed', deviceId: deviceId.slice(0,120), claimedAt: now, updatedAt: now }); return pending.map((x) => ({ ...x.command, status: 'claimed', deviceId, claimedAt: now, updatedAt: now })); }
export async function completeDeviceCommand(profileId: string, commandId: string, deviceId: string, ok: boolean, result?: string) { const handles = await sessionFor(profileId); if (!handles) throw new Error('Device command queue is unavailable.'); const messages = await listHonchoMessages(handles.session, { pageSize: 100, maxPages: 20, reverse: true }); const message = messages.find((m) => m.metadata?.elpDeviceCommand === true && m.metadata?.commandId === commandId); if (!message) throw new Error('Device command not found.'); const now = new Date().toISOString(); await handles.session.updateMessage(message.id, { ...message.metadata, commandStatus: ok ? 'completed' : 'failed', deviceId: deviceId.slice(0,120), completedAt: now, updatedAt: now, result: (result || '').slice(0,1000) }); }
