import { Honcho } from '@honcho-ai/sdk';
import { listHonchoMessages } from '@/lib/honcho-pagination';
export type MobilePushRegistration={deviceId:string;principalId:string;expoPushToken:string;platform:'ios'|'android'|'unknown';enabled:boolean;updatedAt:string;};
function workspaceId(){return process.env.HONCHO_WORKSPACE_ID||'elp-gpt';}
async function sessionFor(profileId:string){if(!process.env.HONCHO_API_KEY)return null;const h=new Honcho({apiKey:process.env.HONCHO_API_KEY,workspaceId:workspaceId(),environment:'production'});const user=await h.peer(`user-${profileId}`);const elp=await h.peer('elp');const session=await h.session(`mobile-companion-${profileId}`);await session.addPeers([user,elp]);return{user,elp,session};}
function parse(m:{metadata:Record<string,unknown>}){if(m.metadata?.elpMobilePush!==true||typeof m.metadata.registrationJson!=='string')return null;try{return JSON.parse(m.metadata.registrationJson) as MobilePushRegistration}catch{return null}}
export async function listMobilePushRegistrations(profileId:string){const h=await sessionFor(profileId);if(!h)return[] as MobilePushRegistration[];const messages=await listHonchoMessages(h.session,{pageSize:100,maxPages:10,reverse:true});const map=new Map<string,MobilePushRegistration>();for(const m of messages){const r=parse(m);if(r&&!map.has(r.deviceId))map.set(r.deviceId,r);}return[...map.values()];}
export async function registerMobilePush(profileId:string,input:{deviceId:string;principalId:string;expoPushToken:string;platform?:string;enabled?:boolean}){const h=await sessionFor(profileId);if(!h)throw new Error('Mobile companion storage is unavailable.');const token=input.expoPushToken.trim().slice(0,300);if(!/^ExponentPushToken\[[^\]]+\]$|^ExpoPushToken\[[^\]]+\]$/.test(token))throw new Error('Invalid Expo push token.');const platform=input.platform==='ios'||input.platform==='android'?input.platform:'unknown';const registration:MobilePushRegistration={deviceId:input.deviceId.trim().slice(0,96),principalId:input.principalId.trim().slice(0,160),expoPushToken:token,platform,enabled:input.enabled!==false,updatedAt:new Date().toISOString()};await h.session.addMessages([{peerId:h.user.id,content:`[MOBILE_PUSH] ${registration.deviceId} ${registration.enabled?'enabled':'disabled'}`,metadata:{elpMobilePush:true,recordVersion:1,registrationJson:JSON.stringify(registration)}}]);return registration;}
export async function sendMobilePush(profileId:string,input:{title:string;body:string;data?:Record<string,unknown>;principalId?:string}){const registrations=(await listMobilePushRegistrations(profileId)).filter((r)=>r.enabled&&(!input.principalId||r.principalId===input.principalId));if(!registrations.length)return{sent:0,failed:0};const payload=registrations.map((r)=>({to:r.expoPushToken,sound:'default',title:input.title.slice(0,120),body:input.body.slice(0,500),data:input.data||{},priority:'high'}));const response=await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15_000)});if(!response.ok)throw new Error(`Mobile push provider returned ${response.status}.`);const result=await response.json().catch(()=>({})) as {data?:Array<{status?:string}>};const rows=Array.isArray(result.data)?result.data:[];return{sent:rows.filter((x)=>x.status==='ok').length||registrations.length,failed:rows.filter((x)=>x.status==='error').length};}
