import { createHmac, createHash } from 'node:crypto';
import { Honcho } from '@honcho-ai/sdk';
import { listHonchoMessages } from '@/lib/honcho-pagination';
import { listSecurityAuditEvents, verifySecurityAuditChain } from '@/lib/security-audit';

export type SecurityAuditExportState={configured:boolean;lastExportedAt?:string;lastEventId?:string;lastHeadHash?:string;lastError?:string;exportedEvents:number;};
function workspaceId(){return process.env.HONCHO_WORKSPACE_ID||'elp-gpt';}
async function sessionFor(profileId:string){if(!process.env.HONCHO_API_KEY)return null;const h=new Honcho({apiKey:process.env.HONCHO_API_KEY,workspaceId:workspaceId(),environment:'production'});const elp=await h.peer('elp');const session=await h.session(`security-audit-export-${profileId}`);await session.addPeers([elp]);return{elp,session};}
function config(){const url=process.env.ELP_SECURITY_AUDIT_SINK_URL?.trim();const secret=process.env.ELP_SECURITY_AUDIT_SINK_SECRET?.trim();if(!url||!secret)return null;try{const parsed=new URL(url);if(parsed.protocol!=='https:')return null;return{url:parsed.toString(),secret};}catch{return null;}}
async function getState(profileId:string):Promise<SecurityAuditExportState>{const c=config();const h=await sessionFor(profileId);if(!h)return{configured:Boolean(c),exportedEvents:0};const messages=await listHonchoMessages(h.session,{pageSize:50,maxPages:5,reverse:true});for(const m of messages){if(m.metadata?.elpSecurityAuditExport===true&&typeof m.metadata.stateJson==='string'){try{return{...JSON.parse(m.metadata.stateJson) as SecurityAuditExportState,configured:Boolean(c)}}catch{}}}return{configured:Boolean(c),exportedEvents:0};}
async function saveState(profileId:string,state:SecurityAuditExportState){const h=await sessionFor(profileId);if(!h)return state;await h.session.addMessages([{peerId:h.elp.id,content:`[SECURITY_AUDIT_EXPORT] ${state.lastExportedAt||new Date().toISOString()}`,metadata:{elpSecurityAuditExport:true,recordVersion:1,stateJson:JSON.stringify(state)}}]);return state;}
export async function getSecurityAuditExportState(profileId:string){return getState(profileId);}
export async function exportSecurityAudit(profileId:string){const c=config();const previous=await getState(profileId);if(!c)return{...previous,configured:false,lastError:'External append-only audit sink is not configured.'};try{const events=await listSecurityAuditEvents(profileId,3000);const integrity=verifySecurityAuditChain(events);if(!integrity.ok)throw new Error(`Audit chain integrity check failed: ${integrity.reason||'unknown failure'}`);const chronological=[...events].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));let start=0;if(previous.lastEventId){const index=chronological.findIndex((e)=>e.id===previous.lastEventId);if(index>=0)start=index+1;}const batch=chronological.slice(start,start+500);if(!batch.length){const state={...previous,configured:true,lastExportedAt:new Date().toISOString(),lastHeadHash:integrity.headHash,lastError:undefined};await saveState(profileId,state);return state;}const body={version:1,profileRef:createHash('sha256').update(profileId).digest('hex').slice(0,24),exportedAt:new Date().toISOString(),previousHeadHash:previous.lastHeadHash||null,headHash:batch.at(-1)?.hash||integrity.headHash||null,events:batch};const raw=JSON.stringify(body);const signature=createHmac('sha256',c.secret).update(raw).digest('hex');const response=await fetch(c.url,{method:'POST',headers:{'Content-Type':'application/json','X-ELP-Audit-Signature':`sha256=${signature}`,'Idempotency-Key':createHash('sha256').update(`${profileId}|${batch[0].id}|${batch.at(-1)?.id}`).digest('hex')},body:raw,signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`Audit sink rejected export (${response.status}).`);const state:SecurityAuditExportState={configured:true,lastExportedAt:new Date().toISOString(),lastEventId:batch.at(-1)?.id,lastHeadHash:batch.at(-1)?.hash,exportedEvents:(previous.exportedEvents||0)+batch.length};await saveState(profileId,state);return state;}catch(error){const state:SecurityAuditExportState={...previous,configured:true,lastError:error instanceof Error?error.message.slice(0,500):'Audit export failed.'};await saveState(profileId,state);return state;}}
