import { randomUUID } from 'node:crypto';
import { Honcho } from '@honcho-ai/sdk';
import { listHonchoMessages } from '@/lib/honcho-pagination';
import { recordSecurityEventSafe } from '@/lib/security-audit';
import { emergencySecurityLockdown, revokePrincipalSecuritySessions, type SecurityOperationsSnapshot } from '@/lib/security-operations';

export type SecurityAutomationAction = 'revoke_subject_sessions' | 'revoke_all_sessions' | 'revoke_all_sessions_and_devices';
export type SecurityAutomationRule = { id:string; name:string; enabled:boolean; findingKey:string; minSeverity:'high'|'critical'; action:SecurityAutomationAction; createdAt:string; updatedAt:string; createdByPrincipalId:string };
export type SecurityAutomationExecution = { id:string; ruleId:string; incidentId:string; findingKey:string; action:SecurityAutomationAction; createdAt:string; ok:boolean; detail:string };
function workspaceId(){return process.env.HONCHO_WORKSPACE_ID||'elp-gpt';}
async function sessionFor(profileId:string){if(!process.env.HONCHO_API_KEY)return null;const h=new Honcho({apiKey:process.env.HONCHO_API_KEY,workspaceId:workspaceId(),environment:'production'});const user=await h.peer(`user-${profileId}`);const elp=await h.peer('elp');const session=await h.session(`security-automation-${profileId}`);await session.addPeers([user,elp]);return{user,elp,session};}
function parseRule(m:{metadata:Record<string,unknown>}){if(m.metadata?.elpSecurityAutomationRule!==true||typeof m.metadata.ruleJson!=='string')return null;try{return JSON.parse(m.metadata.ruleJson) as SecurityAutomationRule}catch{return null}}
function parseExecution(m:{metadata:Record<string,unknown>}){if(m.metadata?.elpSecurityAutomationExecution!==true||typeof m.metadata.executionJson!=='string')return null;try{return JSON.parse(m.metadata.executionJson) as SecurityAutomationExecution}catch{return null}}
export async function listSecurityAutomationRules(profileId:string){const h=await sessionFor(profileId);if(!h)return[] as SecurityAutomationRule[];const messages=await listHonchoMessages(h.session,{pageSize:100,maxPages:15,reverse:true});const map=new Map<string,SecurityAutomationRule>();for(const m of messages){const r=parseRule(m);if(r&&!map.has(r.id))map.set(r.id,r);}return[...map.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
export async function saveSecurityAutomationRule(profileId:string,actorPrincipalId:string,input:Partial<SecurityAutomationRule>&{name:string;findingKey:string;action:SecurityAutomationAction}){const h=await sessionFor(profileId);if(!h)throw new Error('Security automation storage is unavailable.');const current=input.id?(await listSecurityAutomationRules(profileId)).find((r)=>r.id===input.id):undefined;const now=new Date().toISOString();if(!['revoke_subject_sessions','revoke_all_sessions','revoke_all_sessions_and_devices'].includes(input.action))throw new Error('Unsupported security automation action.');const rule:SecurityAutomationRule={id:current?.id||randomUUID(),name:input.name.trim().slice(0,120),enabled:input.enabled===true,findingKey:input.findingKey.trim().slice(0,180),minSeverity:input.minSeverity==='critical'?'critical':'high',action:input.action,createdAt:current?.createdAt||now,updatedAt:now,createdByPrincipalId:current?.createdByPrincipalId||actorPrincipalId};if(!rule.name||!rule.findingKey)throw new Error('Rule name and finding key are required.');await h.session.addMessages([{peerId:h.user.id,content:`[SECURITY_AUTOMATION_RULE] ${rule.name}`,metadata:{elpSecurityAutomationRule:true,recordVersion:1,ruleJson:JSON.stringify(rule)}}]);await recordSecurityEventSafe(profileId,{category:'incident',action:'security_automation.rule_saved',outcome:'success',severity:rule.enabled?'high':'normal',actorPrincipalId,subjectId:rule.id,detail:`${rule.findingKey} => ${rule.action}; enabled=${rule.enabled}`});return rule;}
function severityMeets(actual:'high'|'critical',minimum:'high'|'critical'){return minimum==='high'||actual==='critical';}
export async function applySecurityAutomation(profileId:string,snapshot:SecurityOperationsSnapshot,actorPrincipalId='principal-owner'){
 const h=await sessionFor(profileId);if(!h)return{executed:0,skipped:0,results:[] as SecurityAutomationExecution[]};const [rules,messages]=await Promise.all([listSecurityAutomationRules(profileId),listHonchoMessages(h.session,{pageSize:100,maxPages:20,reverse:true})]);const previous=messages.map(parseExecution).filter((x):x is SecurityAutomationExecution=>Boolean(x));const results:SecurityAutomationExecution[]=[];let skipped=0;
 for(const finding of snapshot.findings){const incident=snapshot.incidents.find((i)=>i.detectionKey===finding.key&&i.status!=='resolved');if(!incident)continue;for(const rule of rules.filter((r)=>r.enabled&&r.findingKey===finding.key&&severityMeets(finding.severity,r.minSeverity))){if(previous.some((x)=>x.ruleId===rule.id&&x.incidentId===incident.id)){skipped++;continue;}let ok=false,detail='';try{if(rule.action==='revoke_subject_sessions'){if(!finding.subjectId)throw new Error('Finding does not identify a principal subject.');const revoked=await revokePrincipalSecuritySessions(profileId,finding.subjectId,actorPrincipalId);detail=`Revoked ${revoked.length} session(s) for ${finding.subjectId}.`;}else{const lockdown=await emergencySecurityLockdown(profileId,actorPrincipalId,rule.action==='revoke_all_sessions_and_devices');detail=`Revoked ${lockdown.revokedSessions.length} session(s) and ${lockdown.revokedDevices.length} device(s).`;}ok=true;}catch(error){detail=error instanceof Error?error.message:'Security automation failed.';}const execution:SecurityAutomationExecution={id:randomUUID(),ruleId:rule.id,incidentId:incident.id,findingKey:finding.key,action:rule.action,createdAt:new Date().toISOString(),ok,detail:detail.slice(0,700)};await h.session.addMessages([{peerId:h.elp.id,content:`[SECURITY_AUTOMATION] ${rule.name}: ${ok?'executed':'failed'}`,metadata:{elpSecurityAutomationExecution:true,recordVersion:1,executionJson:JSON.stringify(execution)}}]);await recordSecurityEventSafe(profileId,{category:'incident',action:'security_automation.executed',outcome:ok?'success':'failure',severity:finding.severity,actorPrincipalId,subjectId:incident.id,detail:`${rule.name}: ${execution.detail}`});results.push(execution);}}
 return{executed:results.filter((x)=>x.ok).length,skipped,results};
}
