import { Honcho } from '@honcho-ai/sdk';
import { listHonchoMessages } from '@/lib/honcho-pagination';
import { upsertNotificationCandidates } from '@/lib/notification-store';
export type TelephonyCallRecord={callId:string;event:string;direction?:string;fromNumber?:string;toNumber?:string;agentId?:string;status?:string;startedAt?:string;endedAt?:string;disconnectionReason?:string;transcriptPreview?:string;updatedAt:string;};
function workspaceId(){return process.env.HONCHO_WORKSPACE_ID||'elp-gpt';}
async function sessionFor(profileId:string){if(!process.env.HONCHO_API_KEY)return null;const h=new Honcho({apiKey:process.env.HONCHO_API_KEY,workspaceId:workspaceId(),environment:'production'});const elp=await h.peer('elp');const session=await h.session(`telephony-${profileId}`);await session.addPeers([elp]);return{elp,session};}
function parse(m:{metadata:Record<string,unknown>}){if(m.metadata?.elpTelephonyCall!==true||typeof m.metadata.callJson!=='string')return null;try{return JSON.parse(m.metadata.callJson) as TelephonyCallRecord}catch{return null}}
export async function recordTelephonyEvent(profileId:string,input:TelephonyCallRecord){const h=await sessionFor(profileId);if(!h)return input;await h.session.addMessages([{peerId:h.elp.id,content:`[TELEPHONY] ${input.event}: ${input.callId}`,metadata:{elpTelephonyCall:true,recordVersion:1,callId:input.callId,event:input.event,callJson:JSON.stringify(input)}}]);const important=['call_ended','call_analyzed'].includes(input.event);if(important)await upsertNotificationCandidates(profileId,[{fingerprint:`telephony-${input.callId}-${input.event}`,kind:'system',severity:input.disconnectionReason&&/error|fail|no_answer/i.test(input.disconnectionReason)?'high':'normal',title:input.direction==='inbound'?'Inbound call completed':'ELP call completed',summary:`${input.direction||'phone'} call ${input.callId}${input.disconnectionReason?` ended: ${input.disconnectionReason}`:''}.`,source:'telephony',sourceId:input.callId,action:'Review call outcome, transcript and any promised follow-up.'}],{resolveMissing:false}).catch(()=>undefined);return input;}
export async function listTelephonyCalls(profileId:string,limit=100){const h=await sessionFor(profileId);if(!h)return[] as TelephonyCallRecord[];const messages=await listHonchoMessages(h.session,{pageSize:100,maxPages:15,reverse:true});const latest=new Map<string,TelephonyCallRecord>();for(const m of messages){const item=parse(m);if(item&&!latest.has(item.callId))latest.set(item.callId,item);}return[...latest.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,Math.max(1,Math.min(500,limit)));}
