import { getExecutiveLedger, type ExecutiveLedger, type ExecutiveLedgerItem } from '@/lib/executive-memory';
import { getPortfolioSnapshot, type GoalRecord, type PortfolioSnapshot } from '@/lib/portfolio-control';
import { getRelationshipSnapshot, type RelationshipRecord, type RelationshipSnapshot } from '@/lib/relationship-memory';
import { getTaskBoard, type TaskBoard, type TaskRecord } from '@/lib/task-router';

export type WorldNodeKind = 'goal' | 'task' | 'artifact' | 'person' | 'organization';
export type WorldEdgeKind = 'parent_of' | 'executes' | 'evidenced_by' | 'supports' | 'implements' | 'informs' | 'depends_on' | 'supersedes' | 'member_of' | 'delegated_to' | 'related_to' | 'same_theme';
export type WorldInsightSeverity = 'critical' | 'high' | 'normal' | 'info';
export type WorldNode = { id:string; kind:WorldNodeKind; label:string; description?:string; status?:string; priority?:string; source:'portfolio'|'tasks'|'executive_ledger'|'relationships'; sourceId:string; tags:string[] };
export type WorldEdge = { id:string; from:string; to:string; type:WorldEdgeKind; confidence:number; source:'explicit'|'inferred'; reason?:string };
export type WorldInsight = { id:string; severity:WorldInsightSeverity; kind:'orphan_execution'|'goal_without_execution'|'goal_risk'|'relationship_attention'|'strategic_connection'; title:string; summary:string; nodeIds:string[] };
export type WorldModel = { configured:boolean; available:boolean; generatedAt:string; nodes:WorldNode[]; edges:WorldEdge[]; insights:WorldInsight[]; stats:{nodes:number;edges:number;explicitEdges:number;inferredEdges:number;goals:number;tasks:number;artifacts:number;people:number;organizations:number;orphanTasks:number;disconnectedGoals:number;attentionRelationships:number} };
export type WorldModelSearch = { query:string; nodes:WorldNode[]; edges:WorldEdge[] };

const STOP_WORDS=new Set(['about','after','again','against','also','and','are','because','before','being','between','but','can','company','could','from','goal','have','into','need','objective','our','should','that','their','them','then','there','these','they','this','those','through','under','very','want','will','with','would','your','task','decision','commitment','assumption','target','today','tomorrow','user','team','principal','elp']);
function clean(value:unknown,max=4000){if(typeof value!=='string')return '';const normalized=value.trim().replace(/\s+/g,' ');return normalized.length<=max?normalized:`${normalized.slice(0,max)}…`;}
function slug(value:string,fallback='unknown'){const normalized=value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return(normalized||fallback).slice(0,96);}
function unique(values:string[],max=20){const seen=new Set<string>();const result:string[]=[];for(const raw of values){const value=clean(raw,180);const key=value.toLowerCase();if(!value||seen.has(key))continue;seen.add(key);result.push(value);if(result.length>=max)break;}return result;}
function tokens(value:string){return new Set(value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9@.+\s-]/g,' ').split(/\s+/).map(token=>token.replace(/^-|-$/g,'')).filter(token=>token.length>=3&&!STOP_WORDS.has(token)));}
function overlap(leftValue:string,rightValue:string){const left=tokens(leftValue);const right=tokens(rightValue);if(!left.size||!right.size)return{shared:0,score:0};let shared=0;for(const token of left)if(right.has(token))shared+=1;return{shared,score:shared/Math.max(3,Math.min(left.size,right.size))};}
function taskList(board:TaskBoard){const all=[...board.queues.now,...board.queues.decisions,...board.queues.working,...board.queues.delegated,...board.queues.done];return all.filter((task,index)=>all.findIndex(candidate=>candidate.id===task.id)===index);}
const goalNodeId=(id:string)=>`goal:${id}`;const taskNodeId=(id:string)=>`task:${id}`;const artifactNodeId=(id:string)=>`artifact:${id}`;const personNodeId=(r:RelationshipRecord)=>`person:${r.key||r.id}`;const organizationNodeId=(name:string)=>`organization:${slug(name)}`;const delegateNodeId=(name:string)=>`person:delegate:${slug(name)}`;
const goalText=(g:GoalRecord)=>[g.title,g.description,g.metric,g.unit].filter(Boolean).join(' ');const taskText=(t:TaskRecord)=>[t.title,t.objective,t.summary,t.progressEvidence,t.note].filter(Boolean).join(' ');const artifactText=(i:ExecutiveLedgerItem)=>[i.title,i.content,i.owner,i.dependencyText,i.note].filter(Boolean).join(' ');const relationshipText=(r:RelationshipRecord)=>[r.name,r.organization,r.role,...r.topics,...r.openLoops,...r.promisesByUs,...r.promisesByThem,r.nextBestAction].filter(Boolean).join(' ');

export function buildWorldModel(input:{portfolio:PortfolioSnapshot;board:TaskBoard;ledger:ExecutiveLedger;relationships:RelationshipSnapshot}):WorldModel{
 const{portfolio,board,ledger,relationships}=input;const nodes:WorldNode[]=[];const edges:WorldEdge[]=[];const insights:WorldInsight[]=[];const nodeIds=new Set<string>();const edgeIds=new Set<string>();
 const addNode=(node:WorldNode)=>{if(!nodeIds.has(node.id)){nodeIds.add(node.id);nodes.push(node);}};
 const addEdge=(edge:Omit<WorldEdge,'id'>)=>{if(!nodeIds.has(edge.from)||!nodeIds.has(edge.to)||edge.from===edge.to)return;const key=`${edge.from}|${edge.type}|${edge.to}`;if(edgeIds.has(key))return;edgeIds.add(key);edges.push({...edge,id:key});};
 for(const g of portfolio.goals)addNode({id:goalNodeId(g.id),kind:'goal',label:g.title,...(g.description?{description:g.description}:{}),status:g.status,priority:g.priority,source:'portfolio',sourceId:g.id,tags:unique([g.level,g.owner,g.metric||'',g.unit||''])});
 const tasks=taskList(board);for(const t of tasks)addNode({id:taskNodeId(t.id),kind:'task',label:t.title,description:t.objective,status:t.status,priority:t.priority,source:'tasks',sourceId:t.id,tags:unique([t.queue,t.owner,t.approval,t.source,t.toolSlug||''])});
 for(const i of ledger.items)addNode({id:artifactNodeId(i.id),kind:'artifact',label:i.title,description:i.content,status:i.status,priority:i.priority,source:'executive_ledger',sourceId:i.id,tags:unique([i.primaryKind,...i.kinds,i.owner||'',i.dependencyText||''])});
 for(const r of relationships.relationships){addNode({id:personNodeId(r),kind:'person',label:r.name,description:[r.organization,r.role,r.nextBestAction].filter(Boolean).join(' · '),status:r.momentum,priority:r.strategicValue,source:'relationships',sourceId:r.id,tags:unique([r.organization||'',r.role||'',...r.topics,...r.openLoops])});if(r.organization)addNode({id:organizationNodeId(r.organization),kind:'organization',label:r.organization,source:'relationships',sourceId:r.organization,tags:unique(r.topics)});}
 for(const g of portfolio.goals){if(g.parentId)addEdge({from:goalNodeId(g.parentId),to:goalNodeId(g.id),type:'parent_of',confidence:1,source:'explicit'});for(const id of g.taskIds)addEdge({from:goalNodeId(g.id),to:taskNodeId(id),type:'executes',confidence:1,source:'explicit'});for(const id of g.ledgerIds)addEdge({from:goalNodeId(g.id),to:artifactNodeId(id),type:'evidenced_by',confidence:1,source:'explicit'});}
 for(const e of ledger.edges){const type=e.type as WorldEdgeKind;if(['supports','implements','informs','depends_on','supersedes'].includes(type))addEdge({from:artifactNodeId(e.from),to:artifactNodeId(e.to),type,confidence:Math.max(0,Math.min(1,e.score)),source:'explicit'});}
 for(const r of relationships.relationships)if(r.organization)addEdge({from:personNodeId(r),to:organizationNodeId(r.organization),type:'member_of',confidence:Math.max(.7,r.confidence),source:'explicit'});
 const normalized=relationships.relationships.map(relationship=>({relationship,match:[relationship.name,relationship.email,relationship.organization].filter(Boolean).join(' ').toLowerCase()}));
 for(const d of portfolio.delegations){const delegatee=clean(d.delegatee,300);if(!delegatee)continue;const needle=delegatee.toLowerCase();const match=normalized.find(x=>x.match.includes(needle)||needle.includes(x.match));const target=match?personNodeId(match.relationship):delegateNodeId(delegatee);if(!match)addNode({id:target,kind:'person',label:delegatee,description:clean(d.expectedOutcome,500),status:d.status,source:'portfolio',sourceId:d.id,tags:unique(['delegatee',d.channel||''])});addEdge({from:taskNodeId(d.taskId),to:target,type:'delegated_to',confidence:1,source:'explicit'});if(d.goalId)addEdge({from:goalNodeId(d.goalId),to:target,type:'delegated_to',confidence:.95,source:'explicit',reason:'Portfolio delegation is attached to this goal.'});}
 const explicitlyLinkedTasks=new Set(edges.filter(e=>e.type==='executes').map(e=>e.to));
 for(const g of portfolio.goals.filter(x=>x.status==='active'||x.status==='at_risk'))for(const t of tasks.filter(x=>x.status==='active'||x.status==='blocked')){if(explicitlyLinkedTasks.has(taskNodeId(t.id)))continue;const r=overlap(goalText(g),taskText(t));if(r.shared>=2&&r.score>=.34)addEdge({from:goalNodeId(g.id),to:taskNodeId(t.id),type:'same_theme',confidence:Math.min(.82,.46+r.score),source:'inferred',reason:`${r.shared} material terms overlap between goal and task.`});}
 for(const g of portfolio.goals.filter(x=>x.status==='active'||x.status==='at_risk'))for(const i of ledger.items.filter(x=>x.status==='active'||x.status==='blocked')){const r=overlap(goalText(g),artifactText(i));if(r.shared>=2&&r.score>=.32)addEdge({from:goalNodeId(g.id),to:artifactNodeId(i.id),type:'same_theme',confidence:Math.min(.8,.44+r.score),source:'inferred',reason:`${r.shared} material terms overlap between goal and executive artifact.`});}
 const strategic=[...portfolio.goals.filter(x=>!['achieved','cancelled'].includes(x.status)).map(x=>({id:goalNodeId(x.id),text:goalText(x)})),...tasks.filter(x=>!['completed','cancelled'].includes(x.status)).map(x=>({id:taskNodeId(x.id),text:taskText(x)})),...ledger.items.filter(x=>!['completed','dismissed','superseded'].includes(x.status)).map(x=>({id:artifactNodeId(x.id),text:artifactText(x)}))];
 for(const rel of relationships.relationships.filter(x=>x.status!=='inactive'))for(const left of strategic){const r=overlap(left.text,relationshipText(rel));if(r.shared>=2&&r.score>=.3)addEdge({from:left.id,to:personNodeId(rel),type:'related_to',confidence:Math.min(.78,.42+r.score),source:'inferred',reason:`${r.shared} material terms connect the work item to this relationship.`});}
 const goalTaskEdges=edges.filter(e=>e.type==='executes'||(e.type==='same_theme'&&e.from.startsWith('goal:')&&e.to.startsWith('task:')));const linkedTaskIds=new Set(goalTaskEdges.map(e=>e.to));const orphanTasks=tasks.filter(t=>!['completed','cancelled'].includes(t.status)&&!linkedTaskIds.has(taskNodeId(t.id)));
 for(const t of orphanTasks.slice(0,12))insights.push({id:`orphan:${t.id}`,severity:t.priority==='critical'?'critical':t.priority==='high'?'high':'normal',kind:'orphan_execution',title:'Execution is not tied to a strategic goal',summary:`${t.title} is active but has no explicit or strong inferred goal link.`,nodeIds:[taskNodeId(t.id)]});
 const disconnectedGoals=portfolio.goals.filter(g=>g.status==='active'&&g.level!=='vision'&&!edges.some(e=>e.from===goalNodeId(g.id)&&['executes','evidenced_by','same_theme'].includes(e.type)));
 for(const g of disconnectedGoals.slice(0,12))insights.push({id:`goal-gap:${g.id}`,severity:g.priority==='critical'?'critical':g.priority==='high'?'high':'normal',kind:'goal_without_execution',title:'Goal has no execution path',summary:`${g.title} is active but has no linked task or executive artifact.`,nodeIds:[goalNodeId(g.id)]});
 for(const h of portfolio.goalHealth.filter(x=>x.health==='critical'||x.health==='at_risk'))insights.push({id:`goal-risk:${h.goal.id}`,severity:h.health==='critical'?'critical':'high',kind:'goal_risk',title:`${h.goal.title} is ${h.health.replace('_',' ')}`,summary:h.reasons.slice(0,3).join(' '),nodeIds:[goalNodeId(h.goal.id)]});
 const attentionRelationships=relationships.relationships.filter(r=>r.status!=='inactive'&&(r.strategicValue==='critical'||r.strategicValue==='high')&&(r.momentum==='cooling'||r.momentum==='stalled'||r.openLoops.length>0));
 for(const r of attentionRelationships.slice(0,12))insights.push({id:`relationship:${r.key}`,severity:r.strategicValue==='critical'&&r.momentum==='stalled'?'critical':'high',kind:'relationship_attention',title:`${r.name} needs attention`,summary:r.nextBestAction||`${r.openLoops.length} open loop${r.openLoops.length===1?'':'s'}; momentum is ${r.momentum}.`,nodeIds:[personNodeId(r)]});
 for(const e of edges.filter(x=>x.source==='inferred'&&x.type==='related_to'&&x.confidence>=.67).slice(0,12)){const left=nodes.find(n=>n.id===e.from);const right=nodes.find(n=>n.id===e.to);if(left&&right)insights.push({id:`connection:${e.id}`,severity:'info',kind:'strategic_connection',title:`Possible strategic connection: ${left.label} ↔ ${right.label}`,summary:e.reason||'ELP detected a strong cross-domain relationship.',nodeIds:[left.id,right.id]});}
 const rank:Record<WorldInsightSeverity,number>={critical:4,high:3,normal:2,info:1};insights.sort((a,b)=>rank[b.severity]-rank[a.severity]||a.title.localeCompare(b.title));nodes.sort((a,b)=>a.kind.localeCompare(b.kind)||a.label.localeCompare(b.label));edges.sort((a,b)=>Number(b.source==='explicit')-Number(a.source==='explicit')||b.confidence-a.confidence);
 return{configured:portfolio.configured||board.configured||ledger.configured||relationships.configured,available:nodes.length>0,generatedAt:new Date().toISOString(),nodes,edges,insights,stats:{nodes:nodes.length,edges:edges.length,explicitEdges:edges.filter(e=>e.source==='explicit').length,inferredEdges:edges.filter(e=>e.source==='inferred').length,goals:nodes.filter(n=>n.kind==='goal').length,tasks:nodes.filter(n=>n.kind==='task').length,artifacts:nodes.filter(n=>n.kind==='artifact').length,people:nodes.filter(n=>n.kind==='person').length,organizations:nodes.filter(n=>n.kind==='organization').length,orphanTasks:orphanTasks.length,disconnectedGoals:disconnectedGoals.length,attentionRelationships:attentionRelationships.length}};
}
export async function getWorldModel(profileId:string):Promise<WorldModel>{const[portfolio,board,ledger,relationships]=await Promise.all([getPortfolioSnapshot(profileId),getTaskBoard(profileId),getExecutiveLedger(profileId),getRelationshipSnapshot(profileId)]);return buildWorldModel({portfolio,board,ledger,relationships});}
export function searchWorldModel(model:WorldModel,query:string,limit=40):WorldModelSearch{const normalized=clean(query,240).toLowerCase();if(!normalized)return{query:'',nodes:model.nodes.slice(0,limit),edges:[]};const queryTokens=[...tokens(normalized)];const ranked=model.nodes.map(node=>{const haystack=[node.label,node.description,node.kind,node.status,node.priority,...node.tags].filter(Boolean).join(' ').toLowerCase();let score=haystack.includes(normalized)?10:0;if(node.label.toLowerCase()===normalized)score+=20;if(node.label.toLowerCase().startsWith(normalized))score+=8;score+=queryTokens.filter(token=>haystack.includes(token)).length*2;return{node,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.node.label.localeCompare(b.node.label)).slice(0,Math.max(1,Math.min(100,limit)));const matched=new Set(ranked.map(x=>x.node.id));const edges=model.edges.filter(e=>matched.has(e.from)||matched.has(e.to)).slice(0,120);const connectedIds=new Set(edges.flatMap(e=>[e.from,e.to]));const connected=model.nodes.filter(n=>connectedIds.has(n.id)&&!matched.has(n.id)).slice(0,20);return{query:normalized,nodes:[...ranked.map(x=>x.node),...connected],edges};}
export function worldModelToPrompt(model:WorldModel){if(!model.available)return'';const critical=model.insights.filter(x=>x.severity==='critical'||x.severity==='high').slice(0,8);const topGoals=model.nodes.filter(n=>n.kind==='goal'&&!['achieved','cancelled'].includes(n.status||'')).slice(0,8);const topPeople=model.nodes.filter(n=>n.kind==='person'&&(n.priority==='critical'||n.priority==='high')).slice(0,8);return[`Operational world model: ${model.stats.nodes} nodes, ${model.stats.edges} links, ${model.stats.orphanTasks} orphan tasks, ${model.stats.disconnectedGoals} goals without execution.`,topGoals.length?`Active strategic goals:\n${topGoals.map(n=>`- ${n.label} [${n.status||'active'}]`).join('\n')}`:'',critical.length?`Cross-domain attention:\n${critical.map(i=>`- ${i.title}: ${i.summary}`).join('\n')}`:'',topPeople.length?`High-value relationships:\n${topPeople.map(n=>`- ${n.label}${n.description?` — ${n.description}`:''}`).join('\n')}`:''].filter(Boolean).join('\n\n');}
