'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Power, RefreshCw, ShieldCheck, Zap } from 'lucide-react';

type Policy={id:string;name:string;enabled:boolean;principalId:string;allowedToolSlugs:string[];maxRisk:'write'|'high';allowHighRisk:boolean;maxActionsPerDay:number;recipientDomains:string[];expiresAt?:string};
type Rule={id:string;name:string;enabled:boolean;findingKey:string;minSeverity:'high'|'critical';action:string};
const panel:React.CSSProperties={background:'#091725',border:'1px solid #1d3c56',borderRadius:14,padding:16};
const button:React.CSSProperties={background:'#10273a',border:'1px solid #315676',borderRadius:9,color:'#e9f5ff',padding:'9px 12px',cursor:'pointer'};
const input:React.CSSProperties={background:'#06111f',border:'1px solid #294863',borderRadius:8,color:'#e9f5ff',padding:'10px 11px',width:'100%'};

export default function AutonomyControl(){
 const [policies,setPolicies]=useState<Policy[]>([]);const [kill,setKill]=useState(false);const [rules,setRules]=useState<Rule[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const [name,setName]=useState('Routine communications');const [tools,setTools]=useState('GMAIL_SEND_EMAIL');const [domains,setDomains]=useState('');const [maxActions,setMaxActions]=useState('10');
 const [ruleName,setRuleName]=useState('Passkey failure response');const [findingKey,setFindingKey]=useState('passkey-failure-burst');
 const load=useCallback(async()=>{setBusy(true);setError('');try{await fetch('/api/identity',{method:'POST',cache:'no-store'});const [a,b]=await Promise.all([fetch('/api/standing-authority',{cache:'no-store'}),fetch('/api/security-automation',{cache:'no-store'})]);const pa=await a.json();const pb=await b.json();if(!a.ok)throw new Error(pa.error||'Could not load standing authority.');if(!b.ok)throw new Error(pb.error||'Could not load security automation.');setPolicies(pa.policies||[]);setKill(pa.killSwitch===true);setRules(pb.rules||[]);}catch(e){setError(e instanceof Error?e.message:'Could not load autonomy control.');}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function post(url:string,body:Record<string,unknown>){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Operation failed.');return payload;}
 async function toggleKill(){setError('');setMessage('');try{await post('/api/standing-authority',{action:'kill-switch',enabled:!kill});setMessage(!kill?'Standing authority stopped globally.':'Standing authority re-enabled.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not change kill switch.');}}
 async function addPolicy(){setError('');setMessage('');try{await post('/api/standing-authority',{action:'save-policy',name,principalId:'principal-owner',allowedToolSlugs:tools.split(',').map(x=>x.trim()).filter(Boolean),recipientDomains:domains.split(',').map(x=>x.trim()).filter(Boolean),maxRisk:'write',allowHighRisk:false,maxActionsPerDay:Number(maxActions)||10,enabled:true});setMessage('Standing authority policy saved.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not save policy.');}}
 async function addRule(){setError('');setMessage('');try{await post('/api/security-automation',{action:'save-rule',name:ruleName,findingKey,ruleAction:'revoke_subject_sessions',minSeverity:'high',enabled:false});setMessage('Security rule saved disabled. Enable it only after reviewing the trigger and response.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not save rule.');}}
 return <main style={{minHeight:'100vh',background:'#06111f',color:'#edf7ff',padding:22,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap',marginBottom:18}}><div><Link href="/mission-control" style={{color:'#9ecbff',textDecoration:'none'}}><ArrowLeft size={16} style={{verticalAlign:'middle'}}/> Mission Control</Link><div style={{fontSize:11,letterSpacing:2,color:'#75a9d6',marginTop:14}}>ELP CONTROLLED AUTONOMY</div><h1 style={{fontSize:34,margin:'4px 0'}}>Standing Authority & Security Automation</h1><p style={{color:'#91aabd',maxWidth:820,margin:0}}>Explicit allowlists, daily limits, expiry, passkey-gated policy changes and an immediate global kill switch. High-risk autonomy is never enabled implicitly.</p></div><button style={button} onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/> Refresh</button></header>
  {error&&<div style={{padding:12,border:'1px solid #78384a',background:'#2a1119',borderRadius:10,color:'#ffd7df',marginBottom:12}}>{error}</div>}{message&&<div style={{padding:12,border:'1px solid #2e6b53',background:'#0a281e',borderRadius:10,color:'#baf5da',marginBottom:12}}>{message}</div>}
  <section style={{...panel,marginBottom:14,display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div><Power size={22}/><b style={{display:'block',fontSize:20,marginTop:7}}>Global kill switch: {kill?'ON':'OFF'}</b><span style={{color:'#91aabd',fontSize:12}}>{kill?'No standing-authority policy can approve external writes.':'Only exact enabled policies can authorize eligible actions.'}</span></div><button style={{...button,borderColor:kill?'#2e6b53':'#8f4057'}} onClick={()=>void toggleKill()}>{kill?'Re-enable standing authority':'STOP standing authority'}</button></section>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:14}}>
   <div style={panel}><ShieldCheck size={22}/><h2>Standing authority</h2><div style={{display:'grid',gap:8}}><input style={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Policy name"/><input style={input} value={tools} onChange={e=>setTools(e.target.value)} placeholder="Exact tool slugs, comma separated"/><input style={input} value={domains} onChange={e=>setDomains(e.target.value)} placeholder="Allowed recipient domains (optional)"/><input style={input} value={maxActions} onChange={e=>setMaxActions(e.target.value)} inputMode="numeric" placeholder="Max actions/day"/><button style={button} onClick={()=>void addPolicy()}>Save passkey-protected policy</button></div><div style={{marginTop:16}}>{policies.map(p=><div key={p.id} style={{padding:'10px 0',borderTop:'1px solid #183149'}}><b>{p.name}</b> <span style={{fontSize:11,color:p.enabled?'#9ce7bf':'#91aabd'}}>{p.enabled?'ENABLED':'DISABLED'}</span><div style={{fontSize:12,color:'#91aabd'}}>{p.allowedToolSlugs.join(', ')} · {p.maxActionsPerDay}/day · risk ≤ {p.maxRisk}</div></div>)}</div></div>
   <div style={panel}><Zap size={22}/><h2>Security automation</h2><p style={{fontSize:12,color:'#91aabd'}}>Rules are created disabled by default. Destructive responses must be explicitly enabled after passkey verification.</p><div style={{display:'grid',gap:8}}><input style={input} value={ruleName} onChange={e=>setRuleName(e.target.value)}/><input style={input} value={findingKey} onChange={e=>setFindingKey(e.target.value)} placeholder="Finding key"/><button style={button} onClick={()=>void addRule()}>Create disabled response rule</button></div><div style={{marginTop:16}}>{rules.map(r=><div key={r.id} style={{padding:'10px 0',borderTop:'1px solid #183149'}}><b>{r.name}</b> <span style={{fontSize:11,color:r.enabled?'#ffc27a':'#91aabd'}}>{r.enabled?'ENABLED':'DISABLED'}</span><div style={{fontSize:12,color:'#91aabd'}}>{r.findingKey} → {r.action}</div></div>)}</div></div>
  </section>
  <footer style={{marginTop:18,color:'#6f8ca4',fontSize:12}}>Computer Operator remains separately scoped by each enrolled device command allowlist. Financial transfers, credential entry, destructive account changes and other high-risk GUI operations are excluded from the visual operator planner.</footer>
 </div></main>;
}
