'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

type Result={objective:string;agents:Array<{id:string;name:string;mission:string}>;evidence:Array<{source:string;query:string;status:string;error?:string}>;findings:Array<{agentName:string;output:string}>;synthesis:string;skills:Array<{id:string;name:string;description:string}>};
export default function HermesTradingPage(){
 const [objective,setObjective]=useState('Find the strongest evidence-backed opportunities in my selected market and build a risk-controlled paper-trading research plan.');
 const [universe,setUniverse]=useState('SPY QQQ AAPL MSFT NVDA BTC-USD ETH-USD'); const [horizon,setHorizon]=useState('1 month'); const [riskBudget,setRiskBudget]=useState('Paper portfolio only; max 1% hypothetical risk per thesis'); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{void fetch('/api/identity',{method:'POST',cache:'no-store'}).catch(()=>undefined);},[]);
 async function run(){setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/hermes-trading',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({objective,universe,horizon,riskBudget})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Mission failed');setResult(j);}catch(e){setError(e instanceof Error?e.message:'Mission failed');}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:'#05070b',color:'#eef2f7',padding:'32px',fontFamily:'system-ui'}}><div style={{maxWidth:1180,margin:'0 auto'}}><Link href="/" style={{color:'#93a4b8',textDecoration:'none'}}>← ELP</Link><p style={{letterSpacing:3,fontSize:12,color:'#8fa3ba',marginTop:28}}>HERMES • AGENTIC MARKET OPERATING SYSTEM</p><h1 style={{fontSize:'clamp(34px,6vw,72px)',margin:'6px 0 12px'}}>Trading Mode</h1><p style={{maxWidth:760,color:'#aab6c5',lineHeight:1.6}}>One objective → verified market tools → specialist agents → competitor/movement analysis → risk veto → backtest → paper portfolio. Live order transmission is disabled.</p><div style={{display:'grid',gap:12,marginTop:28}}><textarea value={objective} onChange={e=>setObjective(e.target.value)} rows={4} style={input}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}><input value={universe} onChange={e=>setUniverse(e.target.value)} placeholder="Universe" style={input}/><input value={horizon} onChange={e=>setHorizon(e.target.value)} placeholder="Horizon" style={input}/><input value={riskBudget} onChange={e=>setRiskBudget(e.target.value)} placeholder="Risk budget" style={input}/></div><button onClick={run} disabled={busy} style={{...input,cursor:'pointer',fontWeight:800,background:'#eef2f7',color:'#080b10'}}>{busy?'Hermes agents running…':'RUN HERMES SWARM'}</button></div>{error&&<p style={{color:'#ff9b9b'}}>{error}</p>}{result&&<><section style={section}><h2>Agent pipeline</h2><div style={grid}>{result.agents.map((a,i)=><article key={a.id} style={card}><b>{String(i+1).padStart(2,'0')} · {a.name}</b><p style={muted}>{a.mission}</p></article>)}</div></section><section style={section}><h2>Connector evidence</h2><div style={grid}>{result.evidence.map((e,i)=><article key={i} style={card}><b>{e.source}</b><p style={muted}>{e.query}</p><p>{e.status}{e.error?` · ${e.error}`:''}</p></article>)}</div></section><section style={section}><h2>Hermes synthesis</h2><pre style={{...card,whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.65}}>{result.synthesis}</pre></section><section style={section}><h2>Video-derived skills</h2><div style={grid}>{result.skills.map(s=><article key={s.id} style={card}><b>{s.name}</b><p style={muted}>{s.description}</p></article>)}</div></section></>}</div></main>}
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',border:'1px solid #263244',borderRadius:12,background:'#0b1018',color:'#eef2f7',padding:'14px 16px',font:'inherit'};const section:React.CSSProperties={marginTop:42};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12};const card:React.CSSProperties={border:'1px solid #202b3a',borderRadius:14,background:'#0a0f16',padding:18};const muted:React.CSSProperties={color:'#9ba9ba',lineHeight:1.5};
