import { NextResponse } from 'next/server';
import { listActivePasskeys } from '@/lib/passkey-memory';
import { validatePrincipalSession } from '@/lib/principal-sessions';
import { verifyPrincipalStepUpToken } from '@/lib/security';
import { assessSecurityOperations } from '@/lib/security-operations';
import { applySecurityAutomation, listSecurityAutomationRules, saveSecurityAutomationRule, type SecurityAutomationAction } from '@/lib/security-automation';
import { requireZeroTrustAuthority } from '@/lib/zero-trust-authority';
export const runtime='nodejs'; export const maxDuration=120;
async function passkeyAuthorized(context:NonNullable<Awaited<ReturnType<typeof requireZeroTrustAuthority>>>,body:Record<string,unknown>|null){if(!(await listActivePasskeys(context.profileId,context.principal.id)).length)return false;const step=verifyPrincipalStepUpToken(typeof body?.stepUpToken==='string'?body.stepUpToken:undefined);if(!step||step.method!=='passkey'||step.purpose!=='authority-management'||step.profileId!==context.profileId||step.principalId!==context.principal.id)return false;if(context.principal.role==='owner')return true;if(!context.session)return false;const live=await validatePrincipalSession({profileId:context.profileId,principalId:context.principal.id,sessionId:context.session.id,tokenVersion:context.session.tokenVersion});return Boolean(live&&step.sessionId===live.id&&step.tokenVersion===live.tokenVersion);}
export async function GET(request:Request){const context=await requireZeroTrustAuthority(request,'manage_authority');if(!context)return NextResponse.json({error:'Authority-management permission is required.'},{status:403});return NextResponse.json({rules:await listSecurityAutomationRules(context.profileId)},{headers:{'Cache-Control':'no-store, private'}});}
export async function POST(request:Request){const context=await requireZeroTrustAuthority(request,'manage_authority');if(!context)return NextResponse.json({error:'Authority-management permission is required.'},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!(await passkeyAuthorized(context,body)))return NextResponse.json({error:'Fresh passkey verification is required for security automation changes or execution.',stepUpRequired:true,stepUpMethod:'passkey'},{status:428});const action=typeof body?.action==='string'?body.action:'';try{if(action==='save-rule'){const raw=typeof body?.ruleAction==='string'?body.ruleAction:'';if(!['revoke_subject_sessions','revoke_all_sessions','revoke_all_sessions_and_devices'].includes(raw))return NextResponse.json({error:'Invalid automation action.'},{status:400});const rule=await saveSecurityAutomationRule(context.profileId,context.principal.id,{id:typeof body?.id==='string'?body.id:undefined,name:typeof body?.name==='string'?body.name:'',findingKey:typeof body?.findingKey==='string'?body.findingKey:'',action:raw as SecurityAutomationAction,minSeverity:body?.minSeverity==='critical'?'critical':'high',enabled:body?.enabled===true});return NextResponse.json({ok:true,rule,rules:await listSecurityAutomationRules(context.profileId)},{status:201});}if(action==='run-now'){const snapshot=await assessSecurityOperations(context.profileId,{persistIncidents:true,notify:true});return NextResponse.json({ok:true,snapshot:{posture:snapshot.posture,findings:snapshot.findings},automation:await applySecurityAutomation(context.profileId,snapshot,context.principal.id)});}return NextResponse.json({error:'Unsupported security-automation action.'},{status:400});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Security automation failed.'},{status:400});}}
