'use client';

import { useEffect, useMemo, useState } from 'react';

type Block = { id: string; kind: string; title: string; start: string; end: string; durationMinutes: number; priorityScore: number; reason: string; recommendedAction?: string; approvalRequired: boolean };
type Schedule = { generatedAt: string; date: string; timezone: string; calendarAvailable: boolean; blocks: Block[]; currentBlockId?: string; nextBlockId?: string; unscheduled: Array<{ id: string; title: string; score: number; recommendedAction: string }>; stats: { focusMinutes: number; deepWorkMinutes: number; prepMinutes: number; bufferMinutes: number; scheduledPriorities: number; unscheduledPriorities: number } };
type Policy = { dayStartHour: number; dayEndHour: number; defaultFocusMinutes: number; minimumFocusMinutes: number; transitionBufferMinutes: number; meetingPrepMinutes: number; maxDeepWorkBlocks: number; protectDeepWork: boolean; timezone: string };

export default function FocusModePage() {
  const [schedule, setSchedule] = useState<Schedule | null>(null); const [policy, setPolicy] = useState<Policy | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const r = await fetch('/api/execution-schedule', { cache: 'no-store' }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to load execution schedule.'); setSchedule(data.schedule); setPolicy(data.policy); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load.'); } finally { setLoading(false); } };
  const refresh = async () => { setLoading(true); setError(''); try { const r = await fetch('/api/execution-schedule', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'refresh' }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Failed to refresh.'); setSchedule(data.schedule); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to refresh.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const format = useMemo(() => new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }), []);
  const current = schedule?.blocks.find((b) => b.id === schedule.currentBlockId); const next = schedule?.blocks.find((b) => b.id === schedule.nextBlockId);
  return <main style={{ minHeight: '100vh', background: '#07111f', color: '#eef5ff', padding: '28px', fontFamily: 'Inter, system-ui, sans-serif' }}>
    <div style={{ maxWidth: 1180, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'center', marginBottom: 24 }}><div><div style={{ fontSize: 13, letterSpacing: 2, color: '#7dd3fc' }}>ELP EXECUTION CONTROL</div><h1 style={{ margin: '6px 0', fontSize: 36 }}>Focus Mode</h1><p style={{ margin: 0, color: '#9fb3c8' }}>Meeting-aware execution blocks generated from the Daily Operating Plan. Calendar changes remain approval-gated.</p></div><button onClick={refresh} disabled={loading} style={{ padding: '11px 16px', borderRadius: 10, border: '1px solid #26445f', background: '#10283b', color: '#fff', cursor: 'pointer' }}>{loading ? 'Refreshing…' : 'Re-plan day'}</button></div>
      {error && <div style={{ padding: 14, border: '1px solid #7f1d1d', borderRadius: 10, marginBottom: 18 }}>{error}</div>}
      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 12, marginBottom: 22 }}>
        {[['Focus', schedule?.stats.focusMinutes || 0, 'min'], ['Deep work', schedule?.stats.deepWorkMinutes || 0, 'min'], ['Prep', schedule?.stats.prepMinutes || 0, 'min'], ['Scheduled', schedule?.stats.scheduledPriorities || 0, 'items'], ['Unscheduled', schedule?.stats.unscheduledPriorities || 0, 'items']].map(([label, value, unit]) => <div key={String(label)} style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 16 }}><div style={{ color: '#8da8bf', fontSize: 12 }}>{label}</div><div style={{ fontSize: 28, marginTop: 4 }}>{String(value)} <span style={{ fontSize: 12, color: '#7890a6' }}>{unit}</span></div></div>)}
      </section>
      <section style={{ display: 'grid', gridTemplateColumns: '1.2fr .8fr', gap: 16, marginBottom: 22 }}>
        <div style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><div style={{ color: '#7dd3fc', fontSize: 12 }}>RIGHT NOW</div><h2 style={{ margin: '8px 0 4px' }}>{current?.title || 'No active protected block'}</h2><div style={{ color: '#9fb3c8' }}>{current ? `${format.format(new Date(current.start))} – ${format.format(new Date(current.end))} · ${current.kind.replaceAll('_', ' ')}` : 'ELP will surface the next scheduled execution block below.'}</div>{current?.recommendedAction && <p>{current.recommendedAction}</p>}</div>
        <div style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><div style={{ color: '#7dd3fc', fontSize: 12 }}>NEXT</div><h3 style={{ margin: '8px 0 4px' }}>{next?.title || 'No next block'}</h3><div style={{ color: '#9fb3c8' }}>{next ? `${format.format(new Date(next.start))} · ${next.durationMinutes} min` : '—'}</div></div>
      </section>
      <section style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18, marginBottom: 22 }}><h2 style={{ marginTop: 0 }}>Today’s execution schedule</h2><div style={{ display: 'grid', gap: 10 }}>{(schedule?.blocks || []).map((b) => <div key={b.id} style={{ display: 'grid', gridTemplateColumns: '120px 1fr 100px', gap: 12, padding: 12, borderRadius: 10, background: b.id === schedule?.currentBlockId ? '#12324a' : '#0a1724' }}><div>{format.format(new Date(b.start))}<div style={{ color: '#7b93aa', fontSize: 12 }}>{b.durationMinutes} min</div></div><div><strong>{b.title}</strong><div style={{ color: '#8fa8be', fontSize: 13, marginTop: 3 }}>{b.kind.replaceAll('_', ' ')} · {b.reason}</div></div><div style={{ textAlign: 'right', color: '#7dd3fc' }}>{b.priorityScore}</div></div>)}{!schedule?.blocks?.length && <div style={{ color: '#9fb3c8' }}>No execution blocks have been generated yet. Use “Re-plan day”.</div>}</div></section>
      <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}><div style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><h3 style={{ marginTop: 0 }}>Operating policy</h3><div style={{ color: '#9fb3c8', lineHeight: 1.8 }}>{policy ? `${policy.dayStartHour}:00–${policy.dayEndHour}:00 · ${policy.defaultFocusMinutes} min focus · ${policy.transitionBufferMinutes} min transitions · ${policy.meetingPrepMinutes} min meeting prep · max ${policy.maxDeepWorkBlocks} deep-work blocks` : 'Loading policy…'}</div></div><div style={{ background: '#0d1d2d', border: '1px solid #1f3850', borderRadius: 14, padding: 18 }}><h3 style={{ marginTop: 0 }}>Unscheduled priorities</h3>{(schedule?.unscheduled || []).slice(0, 6).map((i) => <div key={i.id} style={{ marginBottom: 9 }}><strong>{i.title}</strong><span style={{ color: '#7dd3fc' }}> · {i.score}</span></div>)}{!schedule?.unscheduled?.length && <div style={{ color: '#9fb3c8' }}>No material priority spillover.</div>}</div></section>
    </div>
  </main>;
}
