'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowLeft, BrainCircuit, CalendarClock, CheckCircle2, Clock3, Cpu, Focus, LoaderCircle, LockKeyhole, Phone, RefreshCw, Shield, Target, Users, Zap } from 'lucide-react';

type Priority = { id:string; source:string; sourceId:string; title:string; score:number; priority:string; horizon:string; approvalRequired:boolean; blocked:boolean; recommendedAction:string; reasons:string[] };
type Block = { id:string; kind:string; title:string; start:string; end:string; durationMinutes:number; priorityScore:number; source?:string; sourceId?:string; reason:string; recommendedAction?:string; approvalRequired:boolean };
type Task = { id:string; title:string; objective:string; queue:string; owner:string; priority:string; status:string; progressPercent?:number; remainingHours?:number; estimatedHours?:number; dueAt?:string; progressEvidence?:string };
type Goal = { id:string; title:string; level:string; parentId?:string; owner:string; status:string; priority:string; dueDate?:string; taskIds:string[] };
type Snapshot = {
  generatedAt:string;
  now:Block|null; next:Block|null;
  plan:null|{headline:string;capacityStatus:string;focus:Priority[];blockers:Priority[];stats:{critical:number;blocked:number;decisions:number;overload:boolean}};
  schedule:null|{id:string;date:string;timezone:string;blocks:Block[];unscheduled:Priority[];stats:{focusMinutes:number;deepWorkMinutes:number;scheduledPriorities:number;unscheduledPriorities:number}};
  interrupt:null|{generatedAt:string;decisions:Array<{candidate:{id:string;title:string;severity:string;score:number;summary:string};disposition:string;reason:string}>;checkpoint?:{title:string;remainingMinutes:number};stats:{interruptNow:number;queued:number;monitored:number}};
  board:{queues:Record<string,Task[]>;total:number};
  portfolio:{goals:Goal[];delegations:Array<{id:string;taskId:string;goalId?:string;delegatee:string;status:string;expectedOutcome:string;progress:number;dueDate?:string}>;goalHealth:Array<{goal:Goal;health:string;progress:number;reasons:string[]}>;delegationExceptions:Array<{delegation:{id:string;delegatee:string;expectedOutcome:string;progress:number};severity:string;reason:string;recommendedAction:string}>;stats:{activeGoals:number;criticalGoals:number;atRiskGoals:number;delegatedOpen:number;delegationExceptions:number;orphanTasks:number}};
  capacity:null|{status:string;executionCapacityHours:number;estimatedDemandHours:number;capacityGapHours:number;calendarBusyHours:number;loadRatio:number};
  notifications:{stats:{unread:number;critical:number;high:number;approvals:number;failures:number};notifications:Array<{id:string;severity:string;kind:string;title:string;summary:string}>};
  radar:{stats:{open:number;critical:number;high:number;opportunities:number;risks:number};signals:Array<{id:string;type:string;severity:string;title:string;summary:string;recommendedAction:string}>};
  relationships:{relationships:Array<{id:string;name:string;organization?:string;strategicValue:string;momentum:string;nextBestAction?:string;openLoops:string[]}>};
  diff:{changes:Array<{id:string;kind:string;title:string;summary:string;delta?:number}>;scheduleChanges:Array<{id:string;kind:string;title:string;summary:string}>};
  protectedBlocks:Array<{id:string;label:string;start:string;end:string;immovable:boolean;reason?:string}>;
  eventSubscriptions:Array<{id:string;provider:string;status:string;note?:string;expiresAt?:string}>;
  device:{agentConfigured:boolean;commands:Array<{id:string;type:string;status:string;requestedAt:string;result?:string}>};
  phone:{configured:boolean;available:boolean;phoneNumbers:Array<{number:string;outboundAgentId?:string}>;agents:Array<{id:string;name?:string}>;error?:string};
};
type Pending = { kind:'calendar'|'phone'; summary:string; action:{toolSlug:string;arguments:Record<string,unknown>}; proposalToken:string };

const panel={border:'1px solid #1d3d59',background:'#091827',borderRadius:16,padding:16} as const;
const button={border:'1px solid #315874',background:'#0d2133',color:'#e8f5ff',borderRadius:999,padding:'9px 13px',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:7} as const;
const input={background:'#071421',border:'1px solid #294963',color:'#eaf4ff',borderRadius:9,padding:'9px 10px',width:'100%'} as const;

export default function MissionControlPage(){
  const [data,setData]=useState<Snapshot|null>(null); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [sessionId,setSessionId]=useState('mission-control'); const [pending,setPending]=useState<Pending|null>(null);
  const [protect,setProtect]=useState({label:'',start:'',end:'',reason:''}); const [toNumber,setToNumber]=useState(''); const [fromNumber,setFromNumber]=useState(''); const [agentId,setAgentId]=useState(''); const [purpose,setPurpose]=useState('');
  useEffect(()=>{ const existing=sessionStorage.getItem('elp-session-id'); const id=existing||crypto.randomUUID(); if(!existing) sessionStorage.setItem('elp-session-id',id); setSessionId(id); void fetch('/api/identity',{method:'POST',cache:'no-store'}).then(()=>load()).catch(()=>load()); },[]);
  async function load(){ setBusy('load'); setError(''); try{ const r=await fetch('/api/mission-control',{cache:'no-store'}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Mission Control failed to load.'); setData(j); if(!fromNumber&&j.phone?.phoneNumbers?.[0]) setFromNumber(j.phone.phoneNumbers[0].number); if(!agentId&&j.phone?.agents?.[0]) setAgentId(j.phone.agents[0].id); }catch(e){setError(e instanceof Error?e.message:'Mission Control failed.');} finally{setBusy('');} }
  const tasks=useMemo(()=>data?[...(data.board.queues.now||[]),...(data.board.queues.decisions||[]),...(data.board.queues.working||[]),...(data.board.queues.delegated||[])]:[],[data]);
  async function patchTask(id:string, patch:Record<string,unknown>){ setBusy(`task-${id}`); try{ const r=await fetch('/api/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch})}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Task update failed.'); await load(); }catch(e){setError(e instanceof Error?e.message:'Task update failed.');}finally{setBusy('');} }
  async function createProtected(){ if(!protect.label||!protect.start||!protect.end) return; setBusy('protect'); setError(''); try{ const r=await fetch('/api/protected-blocks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:protect.label,start:new Date(protect.start).toISOString(),end:new Date(protect.end).toISOString(),reason:protect.reason,immovable:true})}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Could not protect block.'); setProtect({label:'',start:'',end:'',reason:''}); setMessage('Protected block saved. ELP will not schedule over it.'); await refreshSchedule(); }catch(e){setError(e instanceof Error?e.message:'Could not protect block.');}finally{setBusy('');} }
  async function refreshSchedule(){ await fetch('/api/daily-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})}); await fetch('/api/execution-schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})}); await load(); }
  async function prepareAction(kind:Pending['kind'], action:{toolSlug:string;arguments:Record<string,unknown>;summary:string}){ setBusy(`prepare-${kind}`); setError(''); setPending(null); try{ const r=await fetch('/api/actions/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,toolSlug:action.toolSlug,arguments:action.arguments,summary:action.summary})}); const j=await r.json(); if(!r.ok||!j.proposalToken) throw new Error(j.error||'Could not prepare approval.'); setPending({kind,summary:action.summary,action:{toolSlug:action.toolSlug,arguments:action.arguments},proposalToken:j.proposalToken}); }catch(e){setError(e instanceof Error?e.message:'Could not prepare action.');}finally{setBusy('');} }
  async function protectCalendarBlock(blockId:string){ setBusy('calendar-spec'); setError(''); try{ const r=await fetch(`/api/execution-calendar-actions?blockId=${encodeURIComponent(blockId)}`,{cache:'no-store'}); const j=await r.json(); if(!r.ok||!j.actions?.[0]?.action) throw new Error(j.error||'No eligible focus block.'); await prepareAction('calendar',j.actions[0].action); }catch(e){setError(e instanceof Error?e.message:'Calendar action failed.'); setBusy('');} }
  async function prepareCall(){ setBusy('phone'); setError(''); try{ const r=await fetch('/api/phone-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare-call',fromNumber,toNumber,agentId,purpose})}); const j=await r.json(); if(!r.ok||!j.pendingAction) throw new Error(j.error||'Call preparation failed.'); await prepareAction('phone',j.pendingAction); }catch(e){setError(e instanceof Error?e.message:'Call preparation failed.'); setBusy('');} }
  async function approve(){ if(!pending)return; setBusy('approve'); setError(''); try{ const a=await fetch('/api/actions/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({proposalToken:pending.proposalToken,sessionId})}); const aj=await a.json(); if(!a.ok||!aj.executionToken) throw new Error(aj.error||'Approval failed.'); const e=await fetch('/api/actions/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:aj.executionToken,sessionId,toolSlug:pending.action.toolSlug,arguments:pending.action.arguments})}); const ej=await e.json(); if(!e.ok||ej.ok===false) throw new Error(ej.error||'Execution failed.'); setMessage(pending.kind==='calendar'?'Calendar focus block created.':'Outbound call started successfully.'); setPending(null); await load(); }catch(err){setError(err instanceof Error?err.message:'Approved action failed.');}finally{setBusy('');} }
  async function enableCalendarRealtime(){setBusy('watch');setError('');try{const r=await fetch('/api/event-subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'watch-google-calendar'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not enable Calendar push.');setMessage('Google Calendar realtime push monitoring enabled.');await load();}catch(e){setError(e instanceof Error?e.message:'Calendar watch failed.');}finally{setBusy('');}}
  async function device(type:string){setBusy(`device-${type}`);setError('');try{const r=await fetch('/api/device-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Device command failed.');setMessage(`Device command queued: ${type}.`);await load();}catch(e){setError(e instanceof Error?e.message:'Device command failed.');}finally{setBusy('');}}
  const time=(v?:string)=>v?new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
  const severityColor=(v:string)=>v==='critical'?'#ff9eab':v==='high'||v==='at_risk'?'#ffd076':v==='healthy'||v==='active'?'#79e2b4':'#8dc6ff';
  return <main style={{minHeight:'100vh',background:'#06111f',color:'#edf7ff',padding:22,fontFamily:'Inter,Arial,sans-serif'}}><div style={{maxWidth:1500,margin:'0 auto'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap',marginBottom:18}}><Link href="/" style={{color:'#9ecbff',textDecoration:'none',display:'flex',gap:7,alignItems:'center'}}><ArrowLeft size={17}/> ELP</Link><div style={{textAlign:'center'}}><div style={{fontSize:11,letterSpacing:2,color:'#75a9d6'}}>ELP EXECUTIVE OPERATING SYSTEM</div><h1 style={{margin:'4px 0',fontSize:34}}>Mission Control</h1><div style={{fontSize:12,color:'#77dfb4'}}>NOW · DECISIONS · EXECUTION · PEOPLE · CAPACITY · REALTIME SIGNALS</div></div><button onClick={()=>void load()} disabled={busy==='load'} style={button}>{busy==='load'?<LoaderCircle size={15}/>:<RefreshCw size={15}/>} Refresh</button></header>
    {error&&<div style={{padding:12,border:'1px solid #773142',background:'#2b1119',borderRadius:10,color:'#ffd8df',marginBottom:12}}>{error}</div>}{message&&<div style={{padding:12,border:'1px solid #2e6a53',background:'#0a281e',borderRadius:10,color:'#b8f5d9',marginBottom:12}}>{message}</div>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,marginBottom:14}}>{[
      ['Critical',data?.plan?.stats.critical||0,<AlertTriangle key="a" size={18}/>],['Decisions',data?.plan?.stats.decisions||0,<BrainCircuit key="b" size={18}/>],['Unread',data?.notifications.stats.unread||0,<Zap key="c" size={18}/>],['At-risk goals',data?.portfolio.stats.atRiskGoals||0,<Target key="d" size={18}/>],['Delegation exceptions',data?.portfolio.stats.delegationExceptions||0,<Users key="e" size={18}/>],['Opportunities',data?.radar.stats.opportunities||0,<Activity key="f" size={18}/>],['Capacity',data?.capacity?.status||'unknown',<Cpu key="g" size={18}/>],
    ].map(([label,value,icon])=><div key={String(label)} style={panel}><div style={{display:'flex',justifyContent:'space-between',color:'#719ec4',fontSize:11,textTransform:'uppercase'}}><span>{label}</span>{icon}</div><div style={{fontSize:26,fontWeight:750,marginTop:7,color:typeof value==='string'?severityColor(value):'#eef7ff'}}>{String(value)}</div></div>)}</section>

    <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) minmax(320px,.6fr)',gap:14,alignItems:'start'}}>
      <div style={{display:'grid',gap:14}}>
        <section style={panel}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><div style={{fontSize:11,color:'#76b7e8',letterSpacing:1.2}}>RIGHT NOW</div><h2 style={{margin:'7px 0'}}>{data?.now?.title||'No active execution block'}</h2><div style={{color:'#9cb4c8'}}>{data?.now?`${time(data.now.start)}–${time(data.now.end)} · ${data.now.kind.replaceAll('_',' ')}`:'ELP is not currently protecting a scheduled block.'}</div>{data?.now?.recommendedAction&&<p style={{lineHeight:1.5}}>{data.now.recommendedAction}</p>}{data?.now&&<button style={button} onClick={()=>void protectCalendarBlock(data.now!.id)}><CalendarClock size={15}/> Put on Calendar</button>}</div><div><div style={{fontSize:11,color:'#76b7e8',letterSpacing:1.2}}>NEXT</div><h3 style={{margin:'7px 0'}}>{data?.next?.title||'No next block'}</h3><div style={{color:'#9cb4c8'}}>{data?.next?`${time(data.next.start)} · ${data.next.durationMinutes} min`:'—'}</div>{data?.next&&<button style={{...button,marginTop:10}} onClick={()=>void protectCalendarBlock(data.next!.id)}><CalendarClock size={15}/> Protect next</button>}</div></div></section>
        {pending&&<section style={{...panel,borderColor:'#826d2d',background:'#231d0c'}}><div style={{fontSize:11,color:'#ffd36d',letterSpacing:1.2}}>EXACT EXTERNAL ACTION — APPROVAL REQUIRED</div><h3>{pending.summary}</h3><pre style={{whiteSpace:'pre-wrap',fontSize:11,color:'#dacfa9',maxHeight:180,overflow:'auto'}}>{JSON.stringify(pending.action.arguments,null,2)}</pre><button style={{...button,borderColor:'#6c8e51'}} onClick={()=>void approve()} disabled={busy==='approve'}><Shield size={15}/> Approve & execute</button></section>}
        <section style={panel}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{margin:0}}>Today’s execution</h3><span style={{fontSize:12,color:'#88a8c0'}}>{data?.schedule?.stats.focusMinutes||0} focus min · {data?.schedule?.stats.unscheduledPriorities||0} spillover</span></div><div style={{display:'grid',gap:8,marginTop:12}}>{(data?.schedule?.blocks||[]).slice(0,14).map(b=><div key={b.id} style={{display:'grid',gridTemplateColumns:'80px 1fr 55px',gap:10,padding:10,borderRadius:9,background:b.id===data?.now?.id?'#12334a':'#071521'}}><span>{time(b.start)}</span><div><b>{b.title}</b><div style={{fontSize:11,color:'#819fb8'}}>{b.kind.replaceAll('_',' ')} · {b.reason}</div></div><span style={{textAlign:'right',color:'#79c6f7'}}>{b.priorityScore}</span></div>)}</div></section>
        <section style={panel}><h3 style={{marginTop:0}}>Command Center progress</h3><div style={{display:'grid',gap:9}}>{tasks.slice(0,16).map(t=><div key={t.id} style={{padding:11,border:'1px solid #203c55',borderRadius:10,background:'#071522'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{t.title}</b><span style={{color:severityColor(t.priority)}}>{t.priority}</span></div><div style={{fontSize:12,color:'#88a4bb',margin:'5px 0'}}>{t.queue.toUpperCase()} · {t.progressPercent??0}% · {t.remainingHours!==undefined?`${t.remainingHours.toFixed(1)}h remaining`:'effort not estimated'}{t.dueAt?` · due ${new Date(t.dueAt).toLocaleString()}`:''}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button style={button} disabled={busy===`task-${t.id}`} onClick={()=>void patchTask(t.id,{progressPercent:Math.min(100,(t.progressPercent??0)+10),progressEvidence:'Progress manually updated from Mission Control.'})}>+10%</button><button style={button} disabled={busy===`task-${t.id}`} onClick={()=>void patchTask(t.id,{status:'completed',queue:'done',progressEvidence:'Marked completed by principal in Mission Control.'})}><CheckCircle2 size={14}/> Complete</button></div></div>)}</div></section>
        <section style={panel}><h3 style={{marginTop:0}}>Why the plan changed</h3>{[...(data?.diff.changes||[]),...(data?.diff.scheduleChanges||[])].slice(0,14).map(c=><div key={`${c.kind}:${c.id}`} style={{padding:'9px 0',borderBottom:'1px solid #173149'}}><b>{c.title}</b><div style={{fontSize:12,color:'#91abc0',marginTop:3}}>{c.kind.replaceAll('_',' ')} · {c.summary}</div></div>)}{!(data?.diff.changes.length||data?.diff.scheduleChanges.length)&&<div style={{color:'#819cb3'}}>No material movement detected between the latest plans.</div>}</section>
        <section style={panel}><h3 style={{marginTop:0}}>Portfolio & delegation</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10}}>{(data?.portfolio.goalHealth||[]).filter(g=>['active','at_risk'].includes(g.goal.status)).slice(0,10).map(g=><div key={g.goal.id} style={{padding:11,border:'1px solid #203e58',borderRadius:10}}><span style={{fontSize:11,color:severityColor(g.health)}}>{g.health.toUpperCase()}</span><b style={{display:'block',marginTop:5}}>{g.goal.title}</b><div style={{fontSize:12,color:'#8aa6bc',marginTop:5}}>{g.progress}% · {g.goal.level.replace('_',' ')}</div></div>)}</div>{(data?.portfolio.delegationExceptions||[]).slice(0,6).map(x=><div key={x.delegation.id} style={{marginTop:9,padding:9,borderLeft:'3px solid #e6ad58',background:'#0b1925'}}><b>{x.delegation.delegatee}: {x.delegation.expectedOutcome}</b><div style={{fontSize:12,color:'#d2b985'}}>{x.reason} — {x.recommendedAction}</div></div>)}<Link href="/portfolio-control" style={{...button,marginTop:12,textDecoration:'none'}}>Open full Portfolio Control</Link></section>
      </div>

      <aside style={{display:'grid',gap:14,position:'sticky',top:12}}>
        <section style={panel}><div style={{display:'flex',alignItems:'center',gap:7}}><LockKeyhole size={17}/><b>Protect time</b></div><div style={{display:'grid',gap:8,marginTop:10}}><input style={input} placeholder="Protected block label" value={protect.label} onChange={e=>setProtect({...protect,label:e.target.value})}/><input style={input} type="datetime-local" value={protect.start} onChange={e=>setProtect({...protect,start:e.target.value})}/><input style={input} type="datetime-local" value={protect.end} onChange={e=>setProtect({...protect,end:e.target.value})}/><input style={input} placeholder="Reason (optional)" value={protect.reason} onChange={e=>setProtect({...protect,reason:e.target.value})}/><button style={button} onClick={()=>void createProtected()} disabled={busy==='protect'}><Focus size={15}/> Lock block</button></div>{(data?.protectedBlocks||[]).slice(0,4).map(b=><div key={b.id} style={{fontSize:11,color:'#8fa8bc',marginTop:8}}>{time(b.start)}–{time(b.end)} · {b.label}</div>)}</section>
        <section style={panel}><div style={{display:'flex',alignItems:'center',gap:7}}><Zap size={17}/><b>Realtime event fabric</b></div><div style={{display:'grid',gap:7,marginTop:10}}>{(data?.eventSubscriptions||[]).map(s=><div key={s.provider} style={{display:'flex',justifyContent:'space-between',gap:8,fontSize:12}}><span>{s.provider.replace('_',' ')}</span><span style={{color:s.status==='active'?'#78e1b5':s.status==='blocked'?'#ff9eab':'#ffd076'}}>{s.status}</span></div>)}</div>{!data?.eventSubscriptions.some(s=>s.provider==='google_calendar'&&s.status==='active')&&<button style={{...button,marginTop:10}} onClick={()=>void enableCalendarRealtime()} disabled={busy==='watch'}><Zap size={14}/> Enable Calendar realtime</button>}</section>
        <section style={panel}><div style={{display:'flex',alignItems:'center',gap:7}}><Phone size={17}/><b>Phone operator</b></div><div style={{fontSize:11,color:data?.phone.available?'#78e1b5':'#d3b878',margin:'7px 0'}}>{data?.phone.available?'Retell phone layer ready':'Phone provider not fully ready'}</div><select style={input} value={fromNumber} onChange={e=>setFromNumber(e.target.value)}>{(data?.phone.phoneNumbers||[]).map(n=><option key={n.number} value={n.number}>{n.number}</option>)}</select><select style={{...input,marginTop:7}} value={agentId} onChange={e=>setAgentId(e.target.value)}>{(data?.phone.agents||[]).map(a=><option key={a.id} value={a.id}>{a.name||a.id}</option>)}</select><input style={{...input,marginTop:7}} placeholder="+14165551234" value={toNumber} onChange={e=>setToNumber(e.target.value)}/><input style={{...input,marginTop:7}} placeholder="Call purpose" value={purpose} onChange={e=>setPurpose(e.target.value)}/><button style={{...button,marginTop:8}} disabled={!data?.phone.available||!toNumber||busy==='phone'} onClick={()=>void prepareCall()}><Phone size={14}/> Prepare call approval</button></section>
        <section style={panel}><div style={{display:'flex',alignItems:'center',gap:7}}><Cpu size={17}/><b>Device control</b></div><div style={{fontSize:11,color:data?.device.agentConfigured?'#78e1b5':'#d3b878',margin:'7px 0'}}>{data?.device.agentConfigured?'Local device agent configured':'Local device agent not configured'}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button style={button} disabled={!data?.device.agentConfigured} onClick={()=>void device('focus_on')}>Focus on</button><button style={button} disabled={!data?.device.agentConfigured} onClick={()=>void device('focus_off')}>Focus off</button><button style={button} disabled={!data?.device.agentConfigured} onClick={()=>void device('lock_screen')}>Lock screen</button></div></section>
        <section style={panel}><h3 style={{marginTop:0}}>Exceptions</h3>{(data?.interrupt?.decisions||[]).filter(d=>d.disposition!=='monitor').slice(0,6).map(d=><div key={d.candidate.id} style={{marginBottom:9}}><b style={{color:severityColor(d.candidate.severity)}}>{d.candidate.title}</b><div style={{fontSize:11,color:'#8ea8bd'}}>{d.disposition.replaceAll('_',' ')} · {d.reason}</div></div>)}{(data?.notifications.notifications||[]).filter(n=>n.severity==='critical'||n.severity==='high').slice(0,5).map(n=><div key={n.id} style={{marginBottom:8,fontSize:12}}><b>{n.title}</b><div style={{color:'#849fb7'}}>{n.kind} · {n.summary}</div></div>)}</section>
        <section style={panel}><h3 style={{marginTop:0}}>Signals & relationships</h3>{(data?.radar.signals||[]).filter(s=>s.type==='opportunity'||s.severity==='critical'||s.severity==='high').slice(0,5).map(s=><div key={s.id} style={{marginBottom:8,fontSize:12}}><b>{s.title}</b><div style={{color:'#849fb7'}}>{s.type} · {s.recommendedAction}</div></div>)}{(data?.relationships.relationships||[]).filter(r=>r.strategicValue==='critical'||r.strategicValue==='high').slice(0,4).map(r=><div key={r.id} style={{fontSize:12,marginTop:7}}><b>{r.name}</b>{r.organization?` · ${r.organization}`:''}<div style={{color:'#849fb7'}}>{r.momentum}{r.nextBestAction?` · ${r.nextBestAction}`:''}</div></div>)}</section>
      </aside>
    </section>
  </div></main>;
}
